// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-service.proto

package com.dunkware.net.proto.data.service;

public final class GDataServiceProto {
  private GDataServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022data-service.proto\022\025dunkware.data.serv" +
      "ice\032\017netstream.proto2p\n\014GDataService\022`\n\014" +
      "streamClient\022%.dunkware.netstream.GNetCl" +
      "ientMessage\032%.dunkware.netstream.GNetSer" +
      "verMessage\"\000(\001B:\n#com.dunkware.net.proto" +
      ".data.serviceB\021GDataServiceProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dunkware.net.proto.netstream.GNetProto.getDescriptor(),
        }, assigner);
    com.dunkware.net.proto.netstream.GNetProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
