/**
 * generated by Xtext 2.21.0
 */
package com.dunkware.xstream.xScript.impl;

import com.dunkware.xstream.xScript.SignalType;
import com.dunkware.xstream.xScript.XScriptPackage;
import com.dunkware.xstream.xScript.XValueHistoricalSignalCountType;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XValue Historical Signal Count Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.dunkware.xstream.xScript.impl.XValueHistoricalSignalCountTypeImpl#getSignal <em>Signal</em>}</li>
 *   <li>{@link com.dunkware.xstream.xScript.impl.XValueHistoricalSignalCountTypeImpl#getDays <em>Days</em>}</li>
 * </ul>
 *
 * @generated
 */
public class XValueHistoricalSignalCountTypeImpl extends XValueTypeImpl implements XValueHistoricalSignalCountType
{
  /**
   * The cached value of the '{@link #getSignal() <em>Signal</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSignal()
   * @generated
   * @ordered
   */
  protected SignalType signal;

  /**
   * The default value of the '{@link #getDays() <em>Days</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDays()
   * @generated
   * @ordered
   */
  protected static final int DAYS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDays() <em>Days</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDays()
   * @generated
   * @ordered
   */
  protected int days = DAYS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XValueHistoricalSignalCountTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XScriptPackage.Literals.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SignalType getSignal()
  {
    if (signal != null && signal.eIsProxy())
    {
      InternalEObject oldSignal = (InternalEObject)signal;
      signal = (SignalType)eResolveProxy(oldSignal);
      if (signal != oldSignal)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__SIGNAL, oldSignal, signal));
      }
    }
    return signal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SignalType basicGetSignal()
  {
    return signal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSignal(SignalType newSignal)
  {
    SignalType oldSignal = signal;
    signal = newSignal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__SIGNAL, oldSignal, signal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getDays()
  {
    return days;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDays(int newDays)
  {
    int oldDays = days;
    days = newDays;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__DAYS, oldDays, days));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__SIGNAL:
        if (resolve) return getSignal();
        return basicGetSignal();
      case XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__DAYS:
        return getDays();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__SIGNAL:
        setSignal((SignalType)newValue);
        return;
      case XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__DAYS:
        setDays((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__SIGNAL:
        setSignal((SignalType)null);
        return;
      case XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__DAYS:
        setDays(DAYS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__SIGNAL:
        return signal != null;
      case XScriptPackage.XVALUE_HISTORICAL_SIGNAL_COUNT_TYPE__DAYS:
        return days != DAYS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (days: ");
    result.append(days);
    result.append(')');
    return result.toString();
  }

} //XValueHistoricalSignalCountTypeImpl
