// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chart.proto

package com.dunkware.net.proto.chart;

public interface GridTransactionUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.chart.GridTransactionUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * json with updated fields plus rowNodeId 
   * </pre>
   *
   * <code>string data = 1;</code>
   */
  java.lang.String getData();
  /**
   * <pre>
   * json with updated fields plus rowNodeId 
   * </pre>
   *
   * <code>string data = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
