package com.dunkware.xstream.xproject.model;


import java.beans.Transient;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import com.dunkware.utils.core.json.DunkJson;
import com.dunkware.utils.core.json.bytes.JsonBytes;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.databind.JsonMappingException;

public class XStreamBundle {

	public static String fuck = "{\"streamBundle\":{\"bytes\":{\"bytes\":\"eyJmaWxlcyI6W3siY29udGVudCI6Ii8qKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqXG4gKiAgVElDSyBEQVRBIElOUFVUUyAxMDAgXG4gKiAqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovICBcbiBzdmFyIFRpY2tTeW1ib2woMSxTVFIpID0gdGljaygyMDIsMCxTVFIpOyAvLyBTZWN1cml0eSBUcmFkaW5nIFN5bWJvbCAgXG4gc3ZhciBUaWNrTGFzdCgyLERVQikgPSB0aWNrKDIwMiwxLERVQik7IC8vIEN1cnJlbnQgUHJpY2UgIFxuIHN2YXIgVGlja1ZvbHVtZSgzLExPTkcpID0gdGljaygyMDIsMjcsTE9ORyk7IC8vIEN1cnJlbnQgVm9sdW1lIFxuIHN2YXIgVGlja1RyYWRlQ291bnQoNCxJTlQpID0gdGljaygyMDIsMzAsSU5UKTsgLy8gQ3VycmVudCBUcmFkZSBDb3VudCBcblxuIC8qKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqXG4gKiAgVElDSyBEQVRBIDEgU0VDT05EIFNOQVBTSE9UUyAyMDAgXG4gKiAqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovXG4gc3ZhciBUaWNrTGFzdDFzZWMoNSxEVUIpID0gc25hcHNob3QoVGlja0xhc3RbMF0pIDEgU0VDOyBcbiBzdmFyIFRpY2tWb2x1bWUxc2VjKDYsTE9ORykgPSBzbmFwc2hvdChUaWNrVm9sdW1lWzBdKSAxIFNFQzsgXG4gc3ZhciBUaWNrVHJhZGVDb3VudDFzZWMoNyxJTlQpID0gc25hcHNob3QoVGlja1RyYWRlQ291bnRbMF0pIDEgU0VDOyBcblxuLyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKipcbiAqICBTSU1QTEUgTU9WSU5HIEFWRVJBR0UgUFJJQ0UgKFNFQ09ORFMpIDEsMDAwIFxuICogKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqL1xuIHN2YXIgU21hMTBzZWMoOCxEVUIpID0gYXZnKHtUaWNrTGFzdDFzZWNbMCw5XX0pOyAvLyAxMCBzZWMgXG4gc3ZhciBTbWEyMHNlYyg5LERVQikgPSBhdmcoe1RpY2tMYXN0MXNlY1swLDE5XX0pOyAvLyAyMCBzZWMgXG4gc3ZhciBTbWEzMHNlYygxMCxEVUIpID0gYXZnKHtUaWNrTGFzdDFzZWNbMCwyOV19KTsgLy8gMzAgc2VjIFxuIHN2YXIgU21hNDBzZWMoMTEsRFVCKSA9IGF2Zyh7VGlja0xhc3Qxc2VjWzAsMzldfSk7IC8vIDQwIHNlYyBcbiBzdmFyIFNtYTUwc2VjKDEyLERVQikgPSBhdmcoe1RpY2tMYXN0MXNlY1swLDQ5XX0pOyAvLyA1MCBzZWNcbiBcbi8qKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqXG4gKiAgU0lNUExFIE1PVklORyBBVkVSQUdFIFBSSUNFIChNSU5VVEVTKSAyLDAwMCBcbiAqICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi9cbiBzdmFyIFNtYTYwc2VjKDEzLERVQikgPSBhdmcoe1RpY2tMYXN0MXNlY1swLDU5XX0pOyAvLyAxIG1pbnV0ZVxuIHN2YXIgU21hOTBzZWMoMTQsRFVCKSA9IGF2Zyh7VGlja0xhc3Qxc2VjWzAsODldfSk7IC8vIDEgbWludXRlXG4gc3ZhciBTbWExMjBzZWMoMTUsRFVCKSA9IGF2Zyh7VGlja0xhc3Qxc2VjWzAsMTE5XX0pOyAvLyAyIG1pbnV0ZSBcbiBzdmFyIFNtYTE1MHNlYygxNixEVUIpID0gYXZnKHtUaWNrTGFzdDFzZWNbMCwxNDldfSk7IC8vIDIgbWludXRlIFxuIHN2YXIgU21hMTgwc2VjKDE3LERVQikgPSBhdmcoe1RpY2tMYXN0MXNlY1swLDE3OV19KTsgLy8gMyBtaW51dGUgXG4gc3ZhciBTbWEyNDBzZWMoMTgsRFVCKSA9IGF2Zyh7VGlja0xhc3Qxc2VjWzAsMjM5XX0pOyAvLyA0IG1pbnV0ZSBcbiBzdmFyIFNtYTMwMHNlYygxOSxEVUIpID0gYXZnKHtUaWNrTGFzdDFzZWNbMCwyOTldfSk7IC8vIDUgbWludXRlIFxuXG4gLyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKipcbiAqIE1PVklORyBWT0xVTUUgQ09VTlRTIChTRUNPTkRTKSA1LDAwMFxuICogKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovXG4gc3ZhciBNdmM1c2VjKDIwLExPTkcpID0gc3ViKFRpY2tWb2x1bWUxc2VjWzBdLFRpY2tWb2x1bWUxc2VjWzRdKTtcbiBzdmFyIE12YzEwc2VjKDIxLExPTkcpID0gc3ViKFRpY2tWb2x1bWUxc2VjWzBdLFRpY2tWb2x1bWUxc2VjWzldKTtcbiBzdmFyIE12YzMwc2VjKDIyLExPTkcpID0gc3ViKFRpY2tWb2x1bWUxc2VjWzBdLFRpY2tWb2x1bWUxc2VjWzI5XSk7XG4gc3ZhciBNdmM2MHNlYygyMyxMT05HKSA9IHN1YihUaWNrVm9sdW1lMXNlY1swXSxUaWNrVm9sdW1lMXNlY1s1OV0pO1xuXG4vKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKlxuICogVk9MVU1FIENPVU5UIEJBUlMgKFNFQ09ORFMpIDYsMDAwXG4gKiAqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi9cblxuIHN2YXIgVmNiNXNlYygyNCxMT05HKSA9IHNuYXBzaG90KHN1YihUaWNrVm9sdW1lMXNlY1swXSxUaWNrVm9sdW1lMXNlY1s0XSkpIDUgU0VDO1xuIHN2YXIgVmNiMTBzZWMoMjUsTE9ORykgPSBzbmFwc2hvdChzdWIoVGlja1ZvbHVtZTFzZWNbMF0sVGlja1ZvbHVtZTFzZWNbOV0pKSAxMCBTRUM7XG4gc3ZhciBWY2IxNXNlYygyNixMT05HKSA9IHNuYXBzaG90KHN1YihUaWNrVm9sdW1lMXNlY1swXSxUaWNrVm9sdW1lMXNlY1sxNF0pKSAxNSBTRUM7XG4gc3ZhciBWY2IzMHNlYygyNyxMT05HKSA9IHNuYXBzaG90KHN1YihUaWNrVm9sdW1lMXNlY1swXSxUaWNrVm9sdW1lMXNlY1syOV0pKSAzMCBTRUM7XG4gc3ZhciBWY2I2MHNlYygyOCxMT05HKSA9IHNuYXBzaG90KHN1YihUaWNrVm9sdW1lMXNlY1swXSxUaWNrVm9sdW1lMXNlY1s1OV0pKSA2MCBTRUM7XG5cbiAvKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKlxuICogTU9WSU5HIFRSQURFIENPVU5UUyAoU0VDT05EUykgNywwMDBcbiAqICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqL1xuXG4gc3ZhciBNdGM1c2VjKDI5LExPTkcpID0gc3ViKFRpY2tUcmFkZUNvdW50MXNlY1swXSxUaWNrVHJhZGVDb3VudDFzZWNbNF0pO1xuIHN2YXIgTXRjMTBzZWMoMzAsTE9ORykgPSBzdWIoVGlja1RyYWRlQ291bnQxc2VjWzBdLFRpY2tUcmFkZUNvdW50MXNlY1s5XSk7XG4gc3ZhciBNdGMxNXNlYygzMSxMT05HKSA9IHN1YihUaWNrVHJhZGVDb3VudDFzZWNbMF0sVGlja1RyYWRlQ291bnQxc2VjWzE0XSk7XG4gc3ZhciBNdGMzMHNlYygzMixMT05HKSA9IHN1YihUaWNrVHJhZGVDb3VudDFzZWNbMF0sVGlja1RyYWRlQ291bnQxc2VjWzI5XSk7XG5cbi8qKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqXG4gKiBUUkFERSBDT1VOVCBCQVJTIChTRUNPTkRTKSA4LDAwMFxuICogKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovXG4gc3ZhciBUY2I1c2VjKDMzLExPTkcpID0gc25hcHNob3Qoc3ViKFRpY2tUcmFkZUNvdW50MXNlY1swXSxUaWNrVHJhZGVDb3VudDFzZWNbNF0pKSA1IFNFQztcbiBzdmFyIFRjYjEwc2VjKDM0LExPTkcpID0gc25hcHNob3Qoc3ViKFRpY2tUcmFkZUNvdW50MXNlY1swXSxUaWNrVHJhZGVDb3VudDFzZWNbOV0pKSAxMCBTRUM7XG4gc3ZhciBUY2IxNXNlYygzNSxMT05HKSA9IHNuYXBzaG90KHN1YihUaWNrVHJhZGVDb3VudDFzZWNbMF0sVGlja1RyYWRlQ291bnQxc2VjWzE0XSkpIDE1IFNFQztcbiBzdmFyIFRjYjMwc2VjKDM2LExPTkcpID0gc25hcHNob3Qoc3ViKFRpY2tUcmFkZUNvdW50MXNlY1swXSxUaWNrVHJhZGVDb3VudDFzZWNbMjldKSkgMzAgU0VDO1xuIHN2YXIgVGNiNjBzZWMoMzcsTE9ORykgPSBzbmFwc2hvdChzdWIoVGlja1RyYWRlQ291bnQxc2VjWzBdLFRpY2tUcmFkZUNvdW50MXNlY1s1OV0pKSA2MCBTRUM7XG5cbi8qKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqXG4gKiBTTUEgUkFURSBPRiBDSEFOR0VTIChTRUNPTkRTKSAzMCwwMDBcbiAqICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqL1xuIFxuIHN2YXIgU21hUm9jMTB4MjBzZWMoMzgsRFVCKSA9IHJvYyhTbWExMHNlY1swXSxTbWEyMHNlY1swXSk7XG4gc3ZhciBTbWFSb2MyMHgzMHNlYygzOSxEVUIpID0gcm9jKFNtYTIwc2VjWzBdLFNtYTMwc2VjWzBdKTtcbiBzdmFyIFNtYVJvYzMweDQwc2VjKDQwLERVQikgPSByb2MoU21hMzBzZWNbMF0sU21hNDBzZWNbMF0pO1xuIHN2YXIgU21hUm9jNDB4NTBzZWMoNDEsRFVCKSA9IHJvYyhTbWE0MHNlY1swXSxTbWE1MHNlY1swXSk7XG4gc3ZhciBTbWFSb2M1MHg2MHNlYyg0MixEVUIpID0gcm9jKFNtYTUwc2VjWzBdLFNtYTYwc2VjWzBdKTtcblxuIC8vIDEgbWludXRlIGluY3JlbWVudFxuIHN2YXIgU21hUm9jNjB4MTIwc2VjKDQzLERVQikgPSByb2MoU21hNjBzZWNbMF0sU21hMTIwc2VjWzBdKTtcbiBzdmFyIFNtYVJvYzEyMHgxNTBzZWMoNDQsRFVCKSA9IHJvYyhTbWExMjBzZWNbMF0sU21hMTUwc2VjWzBdKTtcbiBzdmFyIFNtYVJvYzEyMHgxODBzZWMoNDUsRFVCKSA9IHJvYyhTbWExMjBzZWNbMF0sU21hMTgwc2VjWzBdKTtcbiBzdmFyIFNtYVJvYzE4MHgyNDBzZWMoNDYsRFVCKSA9IHJvYyhTbWExODBzZWNbMF0sU21hMjQwc2VjWzBdKTtcbiBzdmFyIFNtYVJvYzI0MHgzMDBzZWMoNDcsRFVCKSA9IHJvYyhTbWEyNDBzZWNbMF0sU21hMzAwc2VjWzBdKTtcbiBcblxuIFxuIFxuIFNpZ25hbCBCcmVha291dDMwRGF5KDEwMDAsXCJCcmVha291dCAzMCBEYXlcIiwgXCJCcmVha291dHNcIikgU2Nhbm5lciB7IFxuIFx0c2V0dXAgeyBcbiBcdFx0c2NhbkludGVydmFsOiAxIHNlYztcbiBcdH1cbiBcdGNvbmRpdGlvbjogcm9jKE10YzE1c2VjWzBdLHZhckFnZ0hpc3RvcnkoTXRjMTVzZWMsSElHSCxyZWxhdGl2ZURheXMoNCkpID4gMjUuMCk7XG4gXHR9XG4gXHRcbiBcdFxuIFx0XG4gXHRcblxuIFxuIFxuIFxuIn1dfQ==\"},\"extensions\":[{\"@class\":\"com.dunkware.xstream.core.extensions.TimeUpdaterExtType\",\"timeZone\":\"America/New_York\"}],\"date\":\"2024-06-12\",\"timeZone\":\"America/New_York\"},\"stream\":\"us_equity\",\"entitySessionId\":3,\"numericId\":1,\"workerId\":\"US_EQUITY_1\",\"sessionId\":\"us_equity _2024-06-12 18:42:58\",\"nodeId\":\"worker1\",\"kafkaBrokers\":\"localhost:29092\",\"streamId\":1,\"streamProperties\":{\"redist.host\":\"testrock1.dunkware.net\",\"redis.host\":\"testrock1.dunkware.net\",\"redis.port\":\"31673\",\"redis.fuck\":\"dfdfd\"}}";
	
	private JsonBytes bytes;
	@JsonIgnore
	private XScriptBundle scriptBundle;
	private List<XStreamExtensionType> extensions = new ArrayList<XStreamExtensionType>();
	private LocalDate date; 
	private String timeZone;
	
	public static void main(String[] args) {
		
	}
	
	public XStreamBundle() { 
		
	
		
	}
	
	
	

	public List<XStreamExtensionType> getExtensions() {
		return extensions;
	}

	public JsonBytes getBytes() {
		return bytes;
	}

	public void setBytes(JsonBytes bytes) {
		this.bytes = bytes;
		
	}

	@Transient
	public XScriptBundle getScriptBundle() throws JsonMappingException,JsonParseException,IOException {
		if(scriptBundle == null && bytes != null) { 
			this.scriptBundle = DunkJson.getObjectMapper().readValue(bytes.getBytes(), XScriptBundle.class);
		}
		return scriptBundle;
	}

	public void setScriptBundle(XScriptBundle scriptBundle) throws Exception{
		this.scriptBundle = scriptBundle;
		this.bytes = new JsonBytes(DunkJson.getObjectMapper().writeValueAsBytes(scriptBundle));
	}

	public void setExtensions(List<XStreamExtensionType> extensions) {
		this.extensions = extensions;
	}
	
	public LocalDate getDate() {
		return date;
	}

	public void setDate(LocalDate date) {
		this.date = date;
	}

	public String getTimeZone() {
		return timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}
	
	

	
	
	
	// time tick -->??? LocalTimeTick.TYPE - HOUR_FIELD = 1; MINUTE_FIELD = 2; 
	
	
}


