// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chart.proto

package com.dunkware.net.proto.chart;

public interface GridTransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.chart.GridTransaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional list of row updates 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionInsert inserts = 1;</code>
   */
  java.util.List<com.dunkware.net.proto.chart.GridTransactionInsert> 
      getInsertsList();
  /**
   * <pre>
   * Optional list of row updates 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionInsert inserts = 1;</code>
   */
  com.dunkware.net.proto.chart.GridTransactionInsert getInserts(int index);
  /**
   * <pre>
   * Optional list of row updates 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionInsert inserts = 1;</code>
   */
  int getInsertsCount();
  /**
   * <pre>
   * Optional list of row updates 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionInsert inserts = 1;</code>
   */
  java.util.List<? extends com.dunkware.net.proto.chart.GridTransactionInsertOrBuilder> 
      getInsertsOrBuilderList();
  /**
   * <pre>
   * Optional list of row updates 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionInsert inserts = 1;</code>
   */
  com.dunkware.net.proto.chart.GridTransactionInsertOrBuilder getInsertsOrBuilder(
      int index);

  /**
   * <pre>
   * Optional list of row updates 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionUpdate updates = 2;</code>
   */
  java.util.List<com.dunkware.net.proto.chart.GridTransactionUpdate> 
      getUpdatesList();
  /**
   * <pre>
   * Optional list of row updates 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionUpdate updates = 2;</code>
   */
  com.dunkware.net.proto.chart.GridTransactionUpdate getUpdates(int index);
  /**
   * <pre>
   * Optional list of row updates 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionUpdate updates = 2;</code>
   */
  int getUpdatesCount();
  /**
   * <pre>
   * Optional list of row updates 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionUpdate updates = 2;</code>
   */
  java.util.List<? extends com.dunkware.net.proto.chart.GridTransactionUpdateOrBuilder> 
      getUpdatesOrBuilderList();
  /**
   * <pre>
   * Optional list of row updates 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionUpdate updates = 2;</code>
   */
  com.dunkware.net.proto.chart.GridTransactionUpdateOrBuilder getUpdatesOrBuilder(
      int index);

  /**
   * <pre>
   * Optional list of row deletes 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionDelete deletes = 3;</code>
   */
  java.util.List<com.dunkware.net.proto.chart.GridTransactionDelete> 
      getDeletesList();
  /**
   * <pre>
   * Optional list of row deletes 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionDelete deletes = 3;</code>
   */
  com.dunkware.net.proto.chart.GridTransactionDelete getDeletes(int index);
  /**
   * <pre>
   * Optional list of row deletes 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionDelete deletes = 3;</code>
   */
  int getDeletesCount();
  /**
   * <pre>
   * Optional list of row deletes 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionDelete deletes = 3;</code>
   */
  java.util.List<? extends com.dunkware.net.proto.chart.GridTransactionDeleteOrBuilder> 
      getDeletesOrBuilderList();
  /**
   * <pre>
   * Optional list of row deletes 
   * </pre>
   *
   * <code>repeated .dunkware.chart.GridTransactionDelete deletes = 3;</code>
   */
  com.dunkware.net.proto.chart.GridTransactionDeleteOrBuilder getDeletesOrBuilder(
      int index);
}
