/**
 * generated by Xtext 2.31.0
 */
package com.dunkware.xstream.xScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Agg Session Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dunkware.xstream.xScript.VarAggSessionType#getVar <em>Var</em>}</li>
 *   <li>{@link com.dunkware.xstream.xScript.VarAggSessionType#getFunction <em>Function</em>}</li>
 *   <li>{@link com.dunkware.xstream.xScript.VarAggSessionType#getTimeRange <em>Time Range</em>}</li>
 * </ul>
 *
 * @see com.dunkware.xstream.xScript.XScriptPackage#getVarAggSessionType()
 * @model
 * @generated
 */
public interface VarAggSessionType extends ExpressionType
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' reference.
   * @see #setVar(VarType)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getVarAggSessionType_Var()
   * @model
   * @generated
   */
  VarType getVar();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.VarAggSessionType#getVar <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' reference.
   * @see #getVar()
   * @generated
   */
  void setVar(VarType value);

  /**
   * Returns the value of the '<em><b>Function</b></em>' attribute.
   * The literals are from the enumeration {@link com.dunkware.xstream.xScript.SessionAggFunc}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' attribute.
   * @see com.dunkware.xstream.xScript.SessionAggFunc
   * @see #setFunction(SessionAggFunc)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getVarAggSessionType_Function()
   * @model
   * @generated
   */
  SessionAggFunc getFunction();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.VarAggSessionType#getFunction <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' attribute.
   * @see com.dunkware.xstream.xScript.SessionAggFunc
   * @see #getFunction()
   * @generated
   */
  void setFunction(SessionAggFunc value);

  /**
   * Returns the value of the '<em><b>Time Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Range</em>' containment reference.
   * @see #setTimeRange(SessionTimeRange)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getVarAggSessionType_TimeRange()
   * @model containment="true"
   * @generated
   */
  SessionTimeRange getTimeRange();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.VarAggSessionType#getTimeRange <em>Time Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Range</em>' containment reference.
   * @see #getTimeRange()
   * @generated
   */
  void setTimeRange(SessionTimeRange value);

} // VarAggSessionType
