/**
 * generated by Xtext 2.31.0
 */
package com.dunkware.xstream.xScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XFunction Call Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dunkware.xstream.xScript.XFunctionCallType#getFunction <em>Function</em>}</li>
 *   <li>{@link com.dunkware.xstream.xScript.XFunctionCallType#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see com.dunkware.xstream.xScript.XScriptPackage#getXFunctionCallType()
 * @model
 * @generated
 */
public interface XFunctionCallType extends XFunctionCoreElementType
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' reference.
   * @see #setFunction(XFunctionType)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getXFunctionCallType_Function()
   * @model
   * @generated
   */
  XFunctionType getFunction();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.XFunctionCallType#getFunction <em>Function</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(XFunctionType value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' attribute.
   * @see #setParams(String)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getXFunctionCallType_Params()
   * @model
   * @generated
   */
  String getParams();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.XFunctionCallType#getParams <em>Params</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Params</em>' attribute.
   * @see #getParams()
   * @generated
   */
  void setParams(String value);

} // XFunctionCallType
