/**
 * generated by Xtext 2.21.0
 */
package com.dunkware.xstream.xScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XMinus Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dunkware.xstream.xScript.XMinusType#getLeft <em>Left</em>}</li>
 *   <li>{@link com.dunkware.xstream.xScript.XMinusType#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see com.dunkware.xstream.xScript.XScriptPackage#getXMinusType()
 * @model
 * @generated
 */
public interface XMinusType extends XExpressionType
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(XExpressionType)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getXMinusType_Left()
   * @model containment="true"
   * @generated
   */
  XExpressionType getLeft();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.XMinusType#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(XExpressionType value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(XExpressionType)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getXMinusType_Right()
   * @model containment="true"
   * @generated
   */
  XExpressionType getRight();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.XMinusType#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(XExpressionType value);

} // XMinusType
