/**
 * generated by Xtext 2.21.0
 */
package com.dunkware.xstream.xScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XValue Session Var Agg Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dunkware.xstream.xScript.XValueSessionVarAggType#getVar <em>Var</em>}</li>
 *   <li>{@link com.dunkware.xstream.xScript.XValueSessionVarAggType#getFunction <em>Function</em>}</li>
 *   <li>{@link com.dunkware.xstream.xScript.XValueSessionVarAggType#getRange <em>Range</em>}</li>
 * </ul>
 *
 * @see com.dunkware.xstream.xScript.XScriptPackage#getXValueSessionVarAggType()
 * @model
 * @generated
 */
public interface XValueSessionVarAggType extends XValueType
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' reference.
   * @see #setVar(VarType)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getXValueSessionVarAggType_Var()
   * @model
   * @generated
   */
  VarType getVar();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.XValueSessionVarAggType#getVar <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' reference.
   * @see #getVar()
   * @generated
   */
  void setVar(VarType value);

  /**
   * Returns the value of the '<em><b>Function</b></em>' attribute.
   * The literals are from the enumeration {@link com.dunkware.xstream.xScript.XValueVarSessionAggFunction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' attribute.
   * @see com.dunkware.xstream.xScript.XValueVarSessionAggFunction
   * @see #setFunction(XValueVarSessionAggFunction)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getXValueSessionVarAggType_Function()
   * @model
   * @generated
   */
  XValueVarSessionAggFunction getFunction();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.XValueSessionVarAggType#getFunction <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' attribute.
   * @see com.dunkware.xstream.xScript.XValueVarSessionAggFunction
   * @see #getFunction()
   * @generated
   */
  void setFunction(XValueVarSessionAggFunction value);

  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(XTimeRange)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getXValueSessionVarAggType_Range()
   * @model containment="true"
   * @generated
   */
  XTimeRange getRange();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.XValueSessionVarAggType#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(XTimeRange value);

} // XValueSessionVarAggType
