/**
 * generated by Xtext 2.21.0
 */
package com.dunkware.xstream.xScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XValue Var Current Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.dunkware.xstream.xScript.XValueVarCurrentType#getVar <em>Var</em>}</li>
 *   <li>{@link com.dunkware.xstream.xScript.XValueVarCurrentType#getIndex <em>Index</em>}</li>
 * </ul>
 *
 * @see com.dunkware.xstream.xScript.XScriptPackage#getXValueVarCurrentType()
 * @model
 * @generated
 */
public interface XValueVarCurrentType extends XValueType
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' reference.
   * @see #setVar(VarType)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getXValueVarCurrentType_Var()
   * @model
   * @generated
   */
  VarType getVar();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.XValueVarCurrentType#getVar <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' reference.
   * @see #getVar()
   * @generated
   */
  void setVar(VarType value);

  /**
   * Returns the value of the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' attribute.
   * @see #setIndex(int)
   * @see com.dunkware.xstream.xScript.XScriptPackage#getXValueVarCurrentType_Index()
   * @model
   * @generated
   */
  int getIndex();

  /**
   * Sets the value of the '{@link com.dunkware.xstream.xScript.XValueVarCurrentType#getIndex <em>Index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' attribute.
   * @see #getIndex()
   * @generated
   */
  void setIndex(int value);

} // XValueVarCurrentType
