/*
 * Dunkware Street Model
 * Schema for Dunkware Street Model components.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dunkware.street.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.dunkware.street.model.GenTimeRangeType;
import com.dunkware.street.model.GenTimeUnit;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * GenTimeRange
 */
@JsonPropertyOrder({
  GenTimeRange.JSON_PROPERTY_TYPE,
  GenTimeRange.JSON_PROPERTY_START_DATE,
  GenTimeRange.JSON_PROPERTY_END_DATE,
  GenTimeRange.JSON_PROPERTY_RELATIVE_VALUE,
  GenTimeRange.JSON_PROPERTY_RELATIVE_TIME_UNIT,
  GenTimeRange.JSON_PROPERTY_HAS_TIME_WINDOW,
  GenTimeRange.JSON_PROPERTY_TIME_WINDOW
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-14T22:19:41.247179-05:00[America/Chicago]", comments = "Generator version: 7.6.0")
public class GenTimeRange {
  public static final String JSON_PROPERTY_TYPE = "type";
  private GenTimeRangeType type;

  public static final String JSON_PROPERTY_START_DATE = "startDate";
  private Date startDate;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  private Date endDate;

  public static final String JSON_PROPERTY_RELATIVE_VALUE = "relativeValue";
  private Integer relativeValue;

  public static final String JSON_PROPERTY_RELATIVE_TIME_UNIT = "relativeTimeUnit";
  private GenTimeUnit relativeTimeUnit;

  public static final String JSON_PROPERTY_HAS_TIME_WINDOW = "hasTimeWindow";
  private Boolean hasTimeWindow;

  public static final String JSON_PROPERTY_TIME_WINDOW = "timeWindow";
  private GenTimeRange timeWindow;

  public GenTimeRange() { 
  }

  public GenTimeRange type(GenTimeRangeType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GenTimeRangeType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(GenTimeRangeType type) {
    this.type = type;
  }


  public GenTimeRange startDate(Date startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Start date and time of the range.
   * @return startDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getStartDate() {
    return startDate;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }


  public GenTimeRange endDate(Date endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * End date and time of the range.
   * @return endDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Date getEndDate() {
    return endDate;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }


  public GenTimeRange relativeValue(Integer relativeValue) {
    this.relativeValue = relativeValue;
    return this;
  }

   /**
   * The value for the relative time range.
   * @return relativeValue
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATIVE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRelativeValue() {
    return relativeValue;
  }


  @JsonProperty(JSON_PROPERTY_RELATIVE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelativeValue(Integer relativeValue) {
    this.relativeValue = relativeValue;
  }


  public GenTimeRange relativeTimeUnit(GenTimeUnit relativeTimeUnit) {
    this.relativeTimeUnit = relativeTimeUnit;
    return this;
  }

   /**
   * Get relativeTimeUnit
   * @return relativeTimeUnit
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATIVE_TIME_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GenTimeUnit getRelativeTimeUnit() {
    return relativeTimeUnit;
  }


  @JsonProperty(JSON_PROPERTY_RELATIVE_TIME_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelativeTimeUnit(GenTimeUnit relativeTimeUnit) {
    this.relativeTimeUnit = relativeTimeUnit;
  }


  public GenTimeRange hasTimeWindow(Boolean hasTimeWindow) {
    this.hasTimeWindow = hasTimeWindow;
    return this;
  }

   /**
   * Boolean indicating if a specific time window is included in the range.
   * @return hasTimeWindow
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HAS_TIME_WINDOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasTimeWindow() {
    return hasTimeWindow;
  }


  @JsonProperty(JSON_PROPERTY_HAS_TIME_WINDOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasTimeWindow(Boolean hasTimeWindow) {
    this.hasTimeWindow = hasTimeWindow;
  }


  public GenTimeRange timeWindow(GenTimeRange timeWindow) {
    this.timeWindow = timeWindow;
    return this;
  }

   /**
   * Get timeWindow
   * @return timeWindow
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_WINDOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GenTimeRange getTimeWindow() {
    return timeWindow;
  }


  @JsonProperty(JSON_PROPERTY_TIME_WINDOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeWindow(GenTimeRange timeWindow) {
    this.timeWindow = timeWindow;
  }


  /**
   * Return true if this GenTimeRange object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenTimeRange genTimeRange = (GenTimeRange) o;
    return Objects.equals(this.type, genTimeRange.type) &&
        Objects.equals(this.startDate, genTimeRange.startDate) &&
        Objects.equals(this.endDate, genTimeRange.endDate) &&
        Objects.equals(this.relativeValue, genTimeRange.relativeValue) &&
        Objects.equals(this.relativeTimeUnit, genTimeRange.relativeTimeUnit) &&
        Objects.equals(this.hasTimeWindow, genTimeRange.hasTimeWindow) &&
        Objects.equals(this.timeWindow, genTimeRange.timeWindow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, startDate, endDate, relativeValue, relativeTimeUnit, hasTimeWindow, timeWindow);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenTimeRange {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    relativeValue: ").append(toIndentedString(relativeValue)).append("\n");
    sb.append("    relativeTimeUnit: ").append(toIndentedString(relativeTimeUnit)).append("\n");
    sb.append("    hasTimeWindow: ").append(toIndentedString(hasTimeWindow)).append("\n");
    sb.append("    timeWindow: ").append(toIndentedString(timeWindow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `startDate` to the URL query string
    if (getStartDate() != null) {
      joiner.add(String.format("%sstartDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStartDate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `endDate` to the URL query string
    if (getEndDate() != null) {
      joiner.add(String.format("%sendDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEndDate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `relativeValue` to the URL query string
    if (getRelativeValue() != null) {
      joiner.add(String.format("%srelativeValue%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRelativeValue()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `relativeTimeUnit` to the URL query string
    if (getRelativeTimeUnit() != null) {
      joiner.add(getRelativeTimeUnit().toUrlQueryString(prefix + "relativeTimeUnit" + suffix));
    }

    // add `hasTimeWindow` to the URL query string
    if (getHasTimeWindow() != null) {
      joiner.add(String.format("%shasTimeWindow%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHasTimeWindow()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `timeWindow` to the URL query string
    if (getTimeWindow() != null) {
      joiner.add(getTimeWindow().toUrlQueryString(prefix + "timeWindow" + suffix));
    }

    return joiner.toString();
  }
}

