package com.dunkware.trade.broker.tws.scanner;

public enum TwsScannerType {

	
	MOST_ACTIVE,
	HOT_BY_PRICE,
	TOP_VOLUME_RATE,
	TOP_TRADE_COUNT,
	TOP_PRICE_RANGE,
	HOT_BY_VOLUME,
	TOP_TRADE_RATE,
	TOP_PERC_GAIN,
	TOP_PERC_LOSE,
	TOP_OPEN_PERC_GAIN,
	TOP_OPEN_PERC_LOSE
}
