// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package com.dunkware.net.proto.stream;

public interface GEntityTypeCriteriaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.stream.GEntityTypeCriteria)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dunkware.stream.GEntityTypeList types = 1;</code>
   */
  boolean hasTypes();
  /**
   * <code>.dunkware.stream.GEntityTypeList types = 1;</code>
   */
  com.dunkware.net.proto.stream.GEntityTypeList getTypes();
  /**
   * <code>.dunkware.stream.GEntityTypeList types = 1;</code>
   */
  com.dunkware.net.proto.stream.GEntityTypeListOrBuilder getTypesOrBuilder();
}
