// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package com.dunkware.net.proto.stream;

public interface GEntitySearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.stream.GEntitySearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string streamIdentifier = 1;</code>
   */
  java.lang.String getStreamIdentifier();
  /**
   * <code>string streamIdentifier = 1;</code>
   */
  com.google.protobuf.ByteString
      getStreamIdentifierBytes();

  /**
   * <code>.dunkware.stream.GEntityQuery query = 2;</code>
   */
  boolean hasQuery();
  /**
   * <code>.dunkware.stream.GEntityQuery query = 2;</code>
   */
  com.dunkware.net.proto.stream.GEntityQuery getQuery();
  /**
   * <code>.dunkware.stream.GEntityQuery query = 2;</code>
   */
  com.dunkware.net.proto.stream.GEntityQueryOrBuilder getQueryOrBuilder();

  /**
   * <code>repeated string vars = 3;</code>
   */
  java.util.List<java.lang.String>
      getVarsList();
  /**
   * <code>repeated string vars = 3;</code>
   */
  int getVarsCount();
  /**
   * <code>repeated string vars = 3;</code>
   */
  java.lang.String getVars(int index);
  /**
   * <code>repeated string vars = 3;</code>
   */
  com.google.protobuf.ByteString
      getVarsBytes(int index);
}
