// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package com.dunkware.net.proto.stream;

/**
 * <pre>
 * Signal Types Criteria
 * </pre>
 *
 * Protobuf type {@code dunkware.stream.GEntitySignalTypeCriteria}
 */
public  final class GEntitySignalTypeCriteria extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dunkware.stream.GEntitySignalTypeCriteria)
    GEntitySignalTypeCriteriaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GEntitySignalTypeCriteria.newBuilder() to construct.
  private GEntitySignalTypeCriteria(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GEntitySignalTypeCriteria() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GEntitySignalTypeCriteria(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.dunkware.net.proto.stream.GEntitySignalTypeList.Builder subBuilder = null;
            if (types_ != null) {
              subBuilder = types_.toBuilder();
            }
            types_ = input.readMessage(com.dunkware.net.proto.stream.GEntitySignalTypeList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(types_);
              types_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dunkware.net.proto.stream.GStreamProto.internal_static_dunkware_stream_GEntitySignalTypeCriteria_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dunkware.net.proto.stream.GStreamProto.internal_static_dunkware_stream_GEntitySignalTypeCriteria_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dunkware.net.proto.stream.GEntitySignalTypeCriteria.class, com.dunkware.net.proto.stream.GEntitySignalTypeCriteria.Builder.class);
  }

  public static final int TYPES_FIELD_NUMBER = 1;
  private com.dunkware.net.proto.stream.GEntitySignalTypeList types_;
  /**
   * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
   */
  public boolean hasTypes() {
    return types_ != null;
  }
  /**
   * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
   */
  public com.dunkware.net.proto.stream.GEntitySignalTypeList getTypes() {
    return types_ == null ? com.dunkware.net.proto.stream.GEntitySignalTypeList.getDefaultInstance() : types_;
  }
  /**
   * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
   */
  public com.dunkware.net.proto.stream.GEntitySignalTypeListOrBuilder getTypesOrBuilder() {
    return getTypes();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (types_ != null) {
      output.writeMessage(1, getTypes());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (types_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTypes());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dunkware.net.proto.stream.GEntitySignalTypeCriteria)) {
      return super.equals(obj);
    }
    com.dunkware.net.proto.stream.GEntitySignalTypeCriteria other = (com.dunkware.net.proto.stream.GEntitySignalTypeCriteria) obj;

    boolean result = true;
    result = result && (hasTypes() == other.hasTypes());
    if (hasTypes()) {
      result = result && getTypes()
          .equals(other.getTypes());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTypes()) {
      hash = (37 * hash) + TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getTypes().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dunkware.net.proto.stream.GEntitySignalTypeCriteria prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Signal Types Criteria
   * </pre>
   *
   * Protobuf type {@code dunkware.stream.GEntitySignalTypeCriteria}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dunkware.stream.GEntitySignalTypeCriteria)
      com.dunkware.net.proto.stream.GEntitySignalTypeCriteriaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dunkware.net.proto.stream.GStreamProto.internal_static_dunkware_stream_GEntitySignalTypeCriteria_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dunkware.net.proto.stream.GStreamProto.internal_static_dunkware_stream_GEntitySignalTypeCriteria_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dunkware.net.proto.stream.GEntitySignalTypeCriteria.class, com.dunkware.net.proto.stream.GEntitySignalTypeCriteria.Builder.class);
    }

    // Construct using com.dunkware.net.proto.stream.GEntitySignalTypeCriteria.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (typesBuilder_ == null) {
        types_ = null;
      } else {
        types_ = null;
        typesBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dunkware.net.proto.stream.GStreamProto.internal_static_dunkware_stream_GEntitySignalTypeCriteria_descriptor;
    }

    @java.lang.Override
    public com.dunkware.net.proto.stream.GEntitySignalTypeCriteria getDefaultInstanceForType() {
      return com.dunkware.net.proto.stream.GEntitySignalTypeCriteria.getDefaultInstance();
    }

    @java.lang.Override
    public com.dunkware.net.proto.stream.GEntitySignalTypeCriteria build() {
      com.dunkware.net.proto.stream.GEntitySignalTypeCriteria result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dunkware.net.proto.stream.GEntitySignalTypeCriteria buildPartial() {
      com.dunkware.net.proto.stream.GEntitySignalTypeCriteria result = new com.dunkware.net.proto.stream.GEntitySignalTypeCriteria(this);
      if (typesBuilder_ == null) {
        result.types_ = types_;
      } else {
        result.types_ = typesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dunkware.net.proto.stream.GEntitySignalTypeCriteria) {
        return mergeFrom((com.dunkware.net.proto.stream.GEntitySignalTypeCriteria)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dunkware.net.proto.stream.GEntitySignalTypeCriteria other) {
      if (other == com.dunkware.net.proto.stream.GEntitySignalTypeCriteria.getDefaultInstance()) return this;
      if (other.hasTypes()) {
        mergeTypes(other.getTypes());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dunkware.net.proto.stream.GEntitySignalTypeCriteria parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dunkware.net.proto.stream.GEntitySignalTypeCriteria) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.dunkware.net.proto.stream.GEntitySignalTypeList types_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dunkware.net.proto.stream.GEntitySignalTypeList, com.dunkware.net.proto.stream.GEntitySignalTypeList.Builder, com.dunkware.net.proto.stream.GEntitySignalTypeListOrBuilder> typesBuilder_;
    /**
     * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
     */
    public boolean hasTypes() {
      return typesBuilder_ != null || types_ != null;
    }
    /**
     * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
     */
    public com.dunkware.net.proto.stream.GEntitySignalTypeList getTypes() {
      if (typesBuilder_ == null) {
        return types_ == null ? com.dunkware.net.proto.stream.GEntitySignalTypeList.getDefaultInstance() : types_;
      } else {
        return typesBuilder_.getMessage();
      }
    }
    /**
     * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
     */
    public Builder setTypes(com.dunkware.net.proto.stream.GEntitySignalTypeList value) {
      if (typesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        types_ = value;
        onChanged();
      } else {
        typesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
     */
    public Builder setTypes(
        com.dunkware.net.proto.stream.GEntitySignalTypeList.Builder builderForValue) {
      if (typesBuilder_ == null) {
        types_ = builderForValue.build();
        onChanged();
      } else {
        typesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
     */
    public Builder mergeTypes(com.dunkware.net.proto.stream.GEntitySignalTypeList value) {
      if (typesBuilder_ == null) {
        if (types_ != null) {
          types_ =
            com.dunkware.net.proto.stream.GEntitySignalTypeList.newBuilder(types_).mergeFrom(value).buildPartial();
        } else {
          types_ = value;
        }
        onChanged();
      } else {
        typesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
     */
    public Builder clearTypes() {
      if (typesBuilder_ == null) {
        types_ = null;
        onChanged();
      } else {
        types_ = null;
        typesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
     */
    public com.dunkware.net.proto.stream.GEntitySignalTypeList.Builder getTypesBuilder() {
      
      onChanged();
      return getTypesFieldBuilder().getBuilder();
    }
    /**
     * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
     */
    public com.dunkware.net.proto.stream.GEntitySignalTypeListOrBuilder getTypesOrBuilder() {
      if (typesBuilder_ != null) {
        return typesBuilder_.getMessageOrBuilder();
      } else {
        return types_ == null ?
            com.dunkware.net.proto.stream.GEntitySignalTypeList.getDefaultInstance() : types_;
      }
    }
    /**
     * <code>.dunkware.stream.GEntitySignalTypeList types = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dunkware.net.proto.stream.GEntitySignalTypeList, com.dunkware.net.proto.stream.GEntitySignalTypeList.Builder, com.dunkware.net.proto.stream.GEntitySignalTypeListOrBuilder> 
        getTypesFieldBuilder() {
      if (typesBuilder_ == null) {
        typesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dunkware.net.proto.stream.GEntitySignalTypeList, com.dunkware.net.proto.stream.GEntitySignalTypeList.Builder, com.dunkware.net.proto.stream.GEntitySignalTypeListOrBuilder>(
                getTypes(),
                getParentForChildren(),
                isClean());
        types_ = null;
      }
      return typesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dunkware.stream.GEntitySignalTypeCriteria)
  }

  // @@protoc_insertion_point(class_scope:dunkware.stream.GEntitySignalTypeCriteria)
  private static final com.dunkware.net.proto.stream.GEntitySignalTypeCriteria DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dunkware.net.proto.stream.GEntitySignalTypeCriteria();
  }

  public static com.dunkware.net.proto.stream.GEntitySignalTypeCriteria getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GEntitySignalTypeCriteria>
      PARSER = new com.google.protobuf.AbstractParser<GEntitySignalTypeCriteria>() {
    @java.lang.Override
    public GEntitySignalTypeCriteria parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GEntitySignalTypeCriteria(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GEntitySignalTypeCriteria> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GEntitySignalTypeCriteria> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dunkware.net.proto.stream.GEntitySignalTypeCriteria getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

