
# Configure network the initial setup on a new Host via terminal, note this is only required once
# $ docker network create grafana-prometheus
# after this run the below command and the services should start
# grafana default credentials u- admin -p admin
# $ docker compose up
services:
  prometheus:
    image: prom/prometheus
    network_mode: grafana-prometheus
#    network_mode: host
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss
    pull_policy: always
    network_mode: grafana-prometheus
#    network_mode: host
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    ports:
      - 3000:3000
