services:
  prometheus:
    image: prom/prometheus
    network_mode: host
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /Users/ryan/Documents/GitHub/dunkware-street-cloud/projects/dunkware-trade-service-web-server/prometheus.yml/prometheus.yaml:/etc/prometheus/prometheus.yml prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    image: 'grafana/grafana'
    ports:
      - '3000:3000'
