// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web.proto

package com.dunkware.net.proto.web;

public final class GWebProto {
  private GWebProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tweb.proto\022\014dunkware.web\032\014stream.proto\032" +
      "\013chart.proto2\326\001\n\013GWebService\022\\\n\rgetStrea" +
      "mSpec\022#.dunkware.stream.GStreamSpecReque" +
      "st\032$.dunkware.stream.GStreamSpecResponse" +
      "\"\000\022i\n\022autoCompleteSearch\022%.dunkware.stre" +
      "am.GAutoCompleteRequest\032&.dunkware.strea" +
      "m.GAutoCompleteResponse\"\000(\0010\001B)\n\032com.dun" +
      "kware.net.proto.webB\tGWebProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dunkware.net.proto.stream.GStreamProto.getDescriptor(),
          com.dunkware.net.proto.chart.ChartProto.getDescriptor(),
        }, assigner);
    com.dunkware.net.proto.stream.GStreamProto.getDescriptor();
    com.dunkware.net.proto.chart.ChartProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
