// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package com.dunkware.net.proto.core;

public interface GBeanUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.core.GBeanUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 beanId = 1;</code>
   */
  int getBeanId();

  /**
   * <code>repeated .dunkware.core.GField updates = 2;</code>
   */
  java.util.List<com.dunkware.net.proto.core.GField> 
      getUpdatesList();
  /**
   * <code>repeated .dunkware.core.GField updates = 2;</code>
   */
  com.dunkware.net.proto.core.GField getUpdates(int index);
  /**
   * <code>repeated .dunkware.core.GField updates = 2;</code>
   */
  int getUpdatesCount();
  /**
   * <code>repeated .dunkware.core.GField updates = 2;</code>
   */
  java.util.List<? extends com.dunkware.net.proto.core.GFieldOrBuilder> 
      getUpdatesOrBuilderList();
  /**
   * <code>repeated .dunkware.core.GField updates = 2;</code>
   */
  com.dunkware.net.proto.core.GFieldOrBuilder getUpdatesOrBuilder(
      int index);
}
