// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package com.dunkware.net.proto.core;

public interface GTimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.core.GTime)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 hour = 1;</code>
   */
  int getHour();

  /**
   * <code>int32 minute = 2;</code>
   */
  int getMinute();

  /**
   * <code>int32 second = 3;</code>
   */
  int getSecond();
}
