openapi: 3.0.3
info:
  title: Dunkware Blocks 
  description: Reusable Building Blocks For Client & Server Development
  version: 1.1.0


components:
  schemas:
    MetricDash:
      type: object
      properties:
        name:
          type: string
          description: This will be the header title of the metric dash for example "Microsoft Corporation (MSFT)"
        columns:
          type: integer
          description: Define how many columns for rendering the metric cards
        sets:
          type: array
          items:
            $ref: '#/components/schemas/MetricSet'

    MetricSet:
      type: object
      properties:
        name:
          type: string
        cards:
          type: array
          items:
            $ref: '#/components/schemas/MetricCard'

    MetricCard:
      type: object
      properties:
        binding:
          type: string
          description: Json Object data binding field
        name:
          type: string
          description: User UI Metric Name
        format:
          type: string

    SearchEntity:
      type: object
      properties:
        id:
          type: number
          description: ID of the Entity
        symbol:
          type: string
          description: The Ticker Symbol like MSFT
        name:
          type: string
          description: The name of the entity like Microsoft Corporation

    FormatType:
      type: string
      description: The type of format.
      enum:
        - Currency
        - Text
        - Percent
        - Decimal
        - Numeric
