// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netstream.proto

package com.dunkware.net.proto.netstream;

public interface GNetEntityScannerUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.netstream.GNetEntityScannerUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 scannerId = 1;</code>
   */
  int getScannerId();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string error = 3;</code>
   */
  java.lang.String getError();
  /**
   * <code>string error = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
