// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netstream.proto

package com.dunkware.net.proto.netstream;

/**
 * Protobuf type {@code dunkware.netstream.GNetEntitySearchRequest}
 */
public  final class GNetEntitySearchRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dunkware.netstream.GNetEntitySearchRequest)
    GNetEntitySearchRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GNetEntitySearchRequest.newBuilder() to construct.
  private GNetEntitySearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GNetEntitySearchRequest() {
    searchId_ = 0;
    retVars_ = "";
    source_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GNetEntitySearchRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            searchId_ = input.readInt32();
            break;
          }
          case 26: {
            com.dunkware.net.proto.stream.GEntityMatcher.Builder subBuilder = null;
            if (matcher_ != null) {
              subBuilder = matcher_.toBuilder();
            }
            matcher_ = input.readMessage(com.dunkware.net.proto.stream.GEntityMatcher.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(matcher_);
              matcher_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            retVars_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            source_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dunkware.net.proto.netstream.GNetStreamProto.internal_static_dunkware_netstream_GNetEntitySearchRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dunkware.net.proto.netstream.GNetStreamProto.internal_static_dunkware_netstream_GNetEntitySearchRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dunkware.net.proto.netstream.GNetEntitySearchRequest.class, com.dunkware.net.proto.netstream.GNetEntitySearchRequest.Builder.class);
  }

  public static final int SEARCHID_FIELD_NUMBER = 1;
  private int searchId_;
  /**
   * <code>int32 searchId = 1;</code>
   */
  public int getSearchId() {
    return searchId_;
  }

  public static final int MATCHER_FIELD_NUMBER = 3;
  private com.dunkware.net.proto.stream.GEntityMatcher matcher_;
  /**
   * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
   */
  public boolean hasMatcher() {
    return matcher_ != null;
  }
  /**
   * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
   */
  public com.dunkware.net.proto.stream.GEntityMatcher getMatcher() {
    return matcher_ == null ? com.dunkware.net.proto.stream.GEntityMatcher.getDefaultInstance() : matcher_;
  }
  /**
   * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
   */
  public com.dunkware.net.proto.stream.GEntityMatcherOrBuilder getMatcherOrBuilder() {
    return getMatcher();
  }

  public static final int RETVARS_FIELD_NUMBER = 4;
  private volatile java.lang.Object retVars_;
  /**
   * <code>string retVars = 4;</code>
   */
  public java.lang.String getRetVars() {
    java.lang.Object ref = retVars_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      retVars_ = s;
      return s;
    }
  }
  /**
   * <code>string retVars = 4;</code>
   */
  public com.google.protobuf.ByteString
      getRetVarsBytes() {
    java.lang.Object ref = retVars_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      retVars_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_FIELD_NUMBER = 5;
  private volatile java.lang.Object source_;
  /**
   * <code>string source = 5;</code>
   */
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <code>string source = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (searchId_ != 0) {
      output.writeInt32(1, searchId_);
    }
    if (matcher_ != null) {
      output.writeMessage(3, getMatcher());
    }
    if (!getRetVarsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, retVars_);
    }
    if (!getSourceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, source_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (searchId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, searchId_);
    }
    if (matcher_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMatcher());
    }
    if (!getRetVarsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, retVars_);
    }
    if (!getSourceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, source_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dunkware.net.proto.netstream.GNetEntitySearchRequest)) {
      return super.equals(obj);
    }
    com.dunkware.net.proto.netstream.GNetEntitySearchRequest other = (com.dunkware.net.proto.netstream.GNetEntitySearchRequest) obj;

    boolean result = true;
    result = result && (getSearchId()
        == other.getSearchId());
    result = result && (hasMatcher() == other.hasMatcher());
    if (hasMatcher()) {
      result = result && getMatcher()
          .equals(other.getMatcher());
    }
    result = result && getRetVars()
        .equals(other.getRetVars());
    result = result && getSource()
        .equals(other.getSource());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEARCHID_FIELD_NUMBER;
    hash = (53 * hash) + getSearchId();
    if (hasMatcher()) {
      hash = (37 * hash) + MATCHER_FIELD_NUMBER;
      hash = (53 * hash) + getMatcher().hashCode();
    }
    hash = (37 * hash) + RETVARS_FIELD_NUMBER;
    hash = (53 * hash) + getRetVars().hashCode();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dunkware.net.proto.netstream.GNetEntitySearchRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dunkware.netstream.GNetEntitySearchRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dunkware.netstream.GNetEntitySearchRequest)
      com.dunkware.net.proto.netstream.GNetEntitySearchRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dunkware.net.proto.netstream.GNetStreamProto.internal_static_dunkware_netstream_GNetEntitySearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dunkware.net.proto.netstream.GNetStreamProto.internal_static_dunkware_netstream_GNetEntitySearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dunkware.net.proto.netstream.GNetEntitySearchRequest.class, com.dunkware.net.proto.netstream.GNetEntitySearchRequest.Builder.class);
    }

    // Construct using com.dunkware.net.proto.netstream.GNetEntitySearchRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      searchId_ = 0;

      if (matcherBuilder_ == null) {
        matcher_ = null;
      } else {
        matcher_ = null;
        matcherBuilder_ = null;
      }
      retVars_ = "";

      source_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dunkware.net.proto.netstream.GNetStreamProto.internal_static_dunkware_netstream_GNetEntitySearchRequest_descriptor;
    }

    @java.lang.Override
    public com.dunkware.net.proto.netstream.GNetEntitySearchRequest getDefaultInstanceForType() {
      return com.dunkware.net.proto.netstream.GNetEntitySearchRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.dunkware.net.proto.netstream.GNetEntitySearchRequest build() {
      com.dunkware.net.proto.netstream.GNetEntitySearchRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dunkware.net.proto.netstream.GNetEntitySearchRequest buildPartial() {
      com.dunkware.net.proto.netstream.GNetEntitySearchRequest result = new com.dunkware.net.proto.netstream.GNetEntitySearchRequest(this);
      result.searchId_ = searchId_;
      if (matcherBuilder_ == null) {
        result.matcher_ = matcher_;
      } else {
        result.matcher_ = matcherBuilder_.build();
      }
      result.retVars_ = retVars_;
      result.source_ = source_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dunkware.net.proto.netstream.GNetEntitySearchRequest) {
        return mergeFrom((com.dunkware.net.proto.netstream.GNetEntitySearchRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dunkware.net.proto.netstream.GNetEntitySearchRequest other) {
      if (other == com.dunkware.net.proto.netstream.GNetEntitySearchRequest.getDefaultInstance()) return this;
      if (other.getSearchId() != 0) {
        setSearchId(other.getSearchId());
      }
      if (other.hasMatcher()) {
        mergeMatcher(other.getMatcher());
      }
      if (!other.getRetVars().isEmpty()) {
        retVars_ = other.retVars_;
        onChanged();
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dunkware.net.proto.netstream.GNetEntitySearchRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dunkware.net.proto.netstream.GNetEntitySearchRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int searchId_ ;
    /**
     * <code>int32 searchId = 1;</code>
     */
    public int getSearchId() {
      return searchId_;
    }
    /**
     * <code>int32 searchId = 1;</code>
     */
    public Builder setSearchId(int value) {
      
      searchId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 searchId = 1;</code>
     */
    public Builder clearSearchId() {
      
      searchId_ = 0;
      onChanged();
      return this;
    }

    private com.dunkware.net.proto.stream.GEntityMatcher matcher_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dunkware.net.proto.stream.GEntityMatcher, com.dunkware.net.proto.stream.GEntityMatcher.Builder, com.dunkware.net.proto.stream.GEntityMatcherOrBuilder> matcherBuilder_;
    /**
     * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
     */
    public boolean hasMatcher() {
      return matcherBuilder_ != null || matcher_ != null;
    }
    /**
     * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
     */
    public com.dunkware.net.proto.stream.GEntityMatcher getMatcher() {
      if (matcherBuilder_ == null) {
        return matcher_ == null ? com.dunkware.net.proto.stream.GEntityMatcher.getDefaultInstance() : matcher_;
      } else {
        return matcherBuilder_.getMessage();
      }
    }
    /**
     * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
     */
    public Builder setMatcher(com.dunkware.net.proto.stream.GEntityMatcher value) {
      if (matcherBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        matcher_ = value;
        onChanged();
      } else {
        matcherBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
     */
    public Builder setMatcher(
        com.dunkware.net.proto.stream.GEntityMatcher.Builder builderForValue) {
      if (matcherBuilder_ == null) {
        matcher_ = builderForValue.build();
        onChanged();
      } else {
        matcherBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
     */
    public Builder mergeMatcher(com.dunkware.net.proto.stream.GEntityMatcher value) {
      if (matcherBuilder_ == null) {
        if (matcher_ != null) {
          matcher_ =
            com.dunkware.net.proto.stream.GEntityMatcher.newBuilder(matcher_).mergeFrom(value).buildPartial();
        } else {
          matcher_ = value;
        }
        onChanged();
      } else {
        matcherBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
     */
    public Builder clearMatcher() {
      if (matcherBuilder_ == null) {
        matcher_ = null;
        onChanged();
      } else {
        matcher_ = null;
        matcherBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
     */
    public com.dunkware.net.proto.stream.GEntityMatcher.Builder getMatcherBuilder() {
      
      onChanged();
      return getMatcherFieldBuilder().getBuilder();
    }
    /**
     * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
     */
    public com.dunkware.net.proto.stream.GEntityMatcherOrBuilder getMatcherOrBuilder() {
      if (matcherBuilder_ != null) {
        return matcherBuilder_.getMessageOrBuilder();
      } else {
        return matcher_ == null ?
            com.dunkware.net.proto.stream.GEntityMatcher.getDefaultInstance() : matcher_;
      }
    }
    /**
     * <code>.dunkware.stream.GEntityMatcher matcher = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dunkware.net.proto.stream.GEntityMatcher, com.dunkware.net.proto.stream.GEntityMatcher.Builder, com.dunkware.net.proto.stream.GEntityMatcherOrBuilder> 
        getMatcherFieldBuilder() {
      if (matcherBuilder_ == null) {
        matcherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dunkware.net.proto.stream.GEntityMatcher, com.dunkware.net.proto.stream.GEntityMatcher.Builder, com.dunkware.net.proto.stream.GEntityMatcherOrBuilder>(
                getMatcher(),
                getParentForChildren(),
                isClean());
        matcher_ = null;
      }
      return matcherBuilder_;
    }

    private java.lang.Object retVars_ = "";
    /**
     * <code>string retVars = 4;</code>
     */
    public java.lang.String getRetVars() {
      java.lang.Object ref = retVars_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        retVars_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string retVars = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRetVarsBytes() {
      java.lang.Object ref = retVars_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retVars_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string retVars = 4;</code>
     */
    public Builder setRetVars(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      retVars_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string retVars = 4;</code>
     */
    public Builder clearRetVars() {
      
      retVars_ = getDefaultInstance().getRetVars();
      onChanged();
      return this;
    }
    /**
     * <code>string retVars = 4;</code>
     */
    public Builder setRetVarsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      retVars_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object source_ = "";
    /**
     * <code>string source = 5;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source = 5;</code>
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string source = 5;</code>
     */
    public Builder clearSource() {
      
      source_ = getDefaultInstance().getSource();
      onChanged();
      return this;
    }
    /**
     * <code>string source = 5;</code>
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      source_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dunkware.netstream.GNetEntitySearchRequest)
  }

  // @@protoc_insertion_point(class_scope:dunkware.netstream.GNetEntitySearchRequest)
  private static final com.dunkware.net.proto.netstream.GNetEntitySearchRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dunkware.net.proto.netstream.GNetEntitySearchRequest();
  }

  public static com.dunkware.net.proto.netstream.GNetEntitySearchRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GNetEntitySearchRequest>
      PARSER = new com.google.protobuf.AbstractParser<GNetEntitySearchRequest>() {
    @java.lang.Override
    public GNetEntitySearchRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GNetEntitySearchRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GNetEntitySearchRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GNetEntitySearchRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dunkware.net.proto.netstream.GNetEntitySearchRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

