// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netstream.proto

package com.dunkware.net.proto.netstream;

/**
 * Protobuf type {@code dunkware.netstream.GNetEntityScannerRow}
 */
public  final class GNetEntityScannerRow extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dunkware.netstream.GNetEntityScannerRow)
    GNetEntityScannerRowOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GNetEntityScannerRow.newBuilder() to construct.
  private GNetEntityScannerRow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GNetEntityScannerRow() {
    scannerId_ = 0;
    scannerIdent_ = 0;
    entId_ = "";
    data_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GNetEntityScannerRow(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            scannerId_ = input.readInt32();
            break;
          }
          case 16: {

            scannerIdent_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            entId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            data_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dunkware.net.proto.netstream.GNetStreamProto.internal_static_dunkware_netstream_GNetEntityScannerRow_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dunkware.net.proto.netstream.GNetStreamProto.internal_static_dunkware_netstream_GNetEntityScannerRow_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dunkware.net.proto.netstream.GNetEntityScannerRow.class, com.dunkware.net.proto.netstream.GNetEntityScannerRow.Builder.class);
  }

  public static final int SCANNERID_FIELD_NUMBER = 1;
  private int scannerId_;
  /**
   * <code>int32 scannerId = 1;</code>
   */
  public int getScannerId() {
    return scannerId_;
  }

  public static final int SCANNERIDENT_FIELD_NUMBER = 2;
  private int scannerIdent_;
  /**
   * <code>int32 scannerIdent = 2;</code>
   */
  public int getScannerIdent() {
    return scannerIdent_;
  }

  public static final int ENTID_FIELD_NUMBER = 3;
  private volatile java.lang.Object entId_;
  /**
   * <code>string entId = 3;</code>
   */
  public java.lang.String getEntId() {
    java.lang.Object ref = entId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entId_ = s;
      return s;
    }
  }
  /**
   * <code>string entId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEntIdBytes() {
    java.lang.Object ref = entId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 4;
  private volatile java.lang.Object data_;
  /**
   * <code>string data = 4;</code>
   */
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <code>string data = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (scannerId_ != 0) {
      output.writeInt32(1, scannerId_);
    }
    if (scannerIdent_ != 0) {
      output.writeInt32(2, scannerIdent_);
    }
    if (!getEntIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, entId_);
    }
    if (!getDataBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, data_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scannerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, scannerId_);
    }
    if (scannerIdent_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, scannerIdent_);
    }
    if (!getEntIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, entId_);
    }
    if (!getDataBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dunkware.net.proto.netstream.GNetEntityScannerRow)) {
      return super.equals(obj);
    }
    com.dunkware.net.proto.netstream.GNetEntityScannerRow other = (com.dunkware.net.proto.netstream.GNetEntityScannerRow) obj;

    boolean result = true;
    result = result && (getScannerId()
        == other.getScannerId());
    result = result && (getScannerIdent()
        == other.getScannerIdent());
    result = result && getEntId()
        .equals(other.getEntId());
    result = result && getData()
        .equals(other.getData());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCANNERID_FIELD_NUMBER;
    hash = (53 * hash) + getScannerId();
    hash = (37 * hash) + SCANNERIDENT_FIELD_NUMBER;
    hash = (53 * hash) + getScannerIdent();
    hash = (37 * hash) + ENTID_FIELD_NUMBER;
    hash = (53 * hash) + getEntId().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dunkware.net.proto.netstream.GNetEntityScannerRow prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dunkware.netstream.GNetEntityScannerRow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dunkware.netstream.GNetEntityScannerRow)
      com.dunkware.net.proto.netstream.GNetEntityScannerRowOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dunkware.net.proto.netstream.GNetStreamProto.internal_static_dunkware_netstream_GNetEntityScannerRow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dunkware.net.proto.netstream.GNetStreamProto.internal_static_dunkware_netstream_GNetEntityScannerRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dunkware.net.proto.netstream.GNetEntityScannerRow.class, com.dunkware.net.proto.netstream.GNetEntityScannerRow.Builder.class);
    }

    // Construct using com.dunkware.net.proto.netstream.GNetEntityScannerRow.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      scannerId_ = 0;

      scannerIdent_ = 0;

      entId_ = "";

      data_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dunkware.net.proto.netstream.GNetStreamProto.internal_static_dunkware_netstream_GNetEntityScannerRow_descriptor;
    }

    @java.lang.Override
    public com.dunkware.net.proto.netstream.GNetEntityScannerRow getDefaultInstanceForType() {
      return com.dunkware.net.proto.netstream.GNetEntityScannerRow.getDefaultInstance();
    }

    @java.lang.Override
    public com.dunkware.net.proto.netstream.GNetEntityScannerRow build() {
      com.dunkware.net.proto.netstream.GNetEntityScannerRow result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dunkware.net.proto.netstream.GNetEntityScannerRow buildPartial() {
      com.dunkware.net.proto.netstream.GNetEntityScannerRow result = new com.dunkware.net.proto.netstream.GNetEntityScannerRow(this);
      result.scannerId_ = scannerId_;
      result.scannerIdent_ = scannerIdent_;
      result.entId_ = entId_;
      result.data_ = data_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dunkware.net.proto.netstream.GNetEntityScannerRow) {
        return mergeFrom((com.dunkware.net.proto.netstream.GNetEntityScannerRow)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dunkware.net.proto.netstream.GNetEntityScannerRow other) {
      if (other == com.dunkware.net.proto.netstream.GNetEntityScannerRow.getDefaultInstance()) return this;
      if (other.getScannerId() != 0) {
        setScannerId(other.getScannerId());
      }
      if (other.getScannerIdent() != 0) {
        setScannerIdent(other.getScannerIdent());
      }
      if (!other.getEntId().isEmpty()) {
        entId_ = other.entId_;
        onChanged();
      }
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dunkware.net.proto.netstream.GNetEntityScannerRow parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dunkware.net.proto.netstream.GNetEntityScannerRow) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int scannerId_ ;
    /**
     * <code>int32 scannerId = 1;</code>
     */
    public int getScannerId() {
      return scannerId_;
    }
    /**
     * <code>int32 scannerId = 1;</code>
     */
    public Builder setScannerId(int value) {
      
      scannerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 scannerId = 1;</code>
     */
    public Builder clearScannerId() {
      
      scannerId_ = 0;
      onChanged();
      return this;
    }

    private int scannerIdent_ ;
    /**
     * <code>int32 scannerIdent = 2;</code>
     */
    public int getScannerIdent() {
      return scannerIdent_;
    }
    /**
     * <code>int32 scannerIdent = 2;</code>
     */
    public Builder setScannerIdent(int value) {
      
      scannerIdent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 scannerIdent = 2;</code>
     */
    public Builder clearScannerIdent() {
      
      scannerIdent_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object entId_ = "";
    /**
     * <code>string entId = 3;</code>
     */
    public java.lang.String getEntId() {
      java.lang.Object ref = entId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string entId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEntIdBytes() {
      java.lang.Object ref = entId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string entId = 3;</code>
     */
    public Builder setEntId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      entId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string entId = 3;</code>
     */
    public Builder clearEntId() {
      
      entId_ = getDefaultInstance().getEntId();
      onChanged();
      return this;
    }
    /**
     * <code>string entId = 3;</code>
     */
    public Builder setEntIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      entId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object data_ = "";
    /**
     * <code>string data = 4;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string data = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data = 4;</code>
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string data = 4;</code>
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    /**
     * <code>string data = 4;</code>
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      data_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dunkware.netstream.GNetEntityScannerRow)
  }

  // @@protoc_insertion_point(class_scope:dunkware.netstream.GNetEntityScannerRow)
  private static final com.dunkware.net.proto.netstream.GNetEntityScannerRow DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dunkware.net.proto.netstream.GNetEntityScannerRow();
  }

  public static com.dunkware.net.proto.netstream.GNetEntityScannerRow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GNetEntityScannerRow>
      PARSER = new com.google.protobuf.AbstractParser<GNetEntityScannerRow>() {
    @java.lang.Override
    public GNetEntityScannerRow parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GNetEntityScannerRow(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GNetEntityScannerRow> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GNetEntityScannerRow> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dunkware.net.proto.netstream.GNetEntityScannerRow getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

