// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netstream.proto

package com.dunkware.net.proto.netstream;

public interface GNetEntityScannerStartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.netstream.GNetEntityScannerStartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scannerIdent = 1;</code>
   */
  java.lang.String getScannerIdent();
  /**
   * <code>string scannerIdent = 1;</code>
   */
  com.google.protobuf.ByteString
      getScannerIdentBytes();

  /**
   * <code>.dunkware.netstream.GEntityMatcher matcher = 3;</code>
   */
  boolean hasMatcher();
  /**
   * <code>.dunkware.netstream.GEntityMatcher matcher = 3;</code>
   */
  com.dunkware.net.proto.netstream.GEntityMatcher getMatcher();
  /**
   * <code>.dunkware.netstream.GEntityMatcher matcher = 3;</code>
   */
  com.dunkware.net.proto.netstream.GEntityMatcherOrBuilder getMatcherOrBuilder();

  /**
   * <code>repeated string retVars = 4;</code>
   */
  java.util.List<java.lang.String>
      getRetVarsList();
  /**
   * <code>repeated string retVars = 4;</code>
   */
  int getRetVarsCount();
  /**
   * <code>repeated string retVars = 4;</code>
   */
  java.lang.String getRetVars(int index);
  /**
   * <code>repeated string retVars = 4;</code>
   */
  com.google.protobuf.ByteString
      getRetVarsBytes(int index);
}
