/*
 * Dunkware Street Model
 * Schema for Dunkware Street Model components.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dunkware.street.model;

import com.dunkware.street.model.GenDate;
import com.dunkware.street.model.GenTime;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TickerSession
 */
class TickerSessionTest {
    private final TickerSession model = new TickerSession();

    /**
     * Model tests for TickerSession
     */
    @Test
    void testTickerSession() {
        // TODO: test TickerSession
    }

    /**
     * Test the property 'date'
     */
    @Test
    void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'stopTime'
     */
    @Test
    void stopTimeTest() {
        // TODO: test stopTime
    }

    /**
     * Test the property 'signalCount'
     */
    @Test
    void signalCountTest() {
        // TODO: test signalCount
    }

    /**
     * Test the property 'version'
     */
    @Test
    void versionTest() {
        // TODO: test version
    }

}
