// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cluster.proto

package com.dunkware.trade.service.stream.json.cluster.protocol;

public final class ClusterProto {
  private ClusterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodePingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string birthday = 1;</code>
     */
    boolean hasBirthday();
    /**
     * <code>required string birthday = 1;</code>
     */
    java.lang.String getBirthday();
    /**
     * <code>required string birthday = 1;</code>
     */
    com.google.protobuf.ByteString
        getBirthdayBytes();

    /**
     * <code>required string id = 3;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 3;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 3;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string endPoint = 4;</code>
     */
    boolean hasEndPoint();
    /**
     * <code>required string endPoint = 4;</code>
     */
    java.lang.String getEndPoint();
    /**
     * <code>required string endPoint = 4;</code>
     */
    com.google.protobuf.ByteString
        getEndPointBytes();

    /**
     * <code>required .com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing.NodePingStatus status = 5;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing.NodePingStatus status = 5;</code>
     */
    com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus getStatus();

    /**
     * <code>repeated string profiles = 6;</code>
     */
    java.util.List<java.lang.String>
        getProfilesList();
    /**
     * <code>repeated string profiles = 6;</code>
     */
    int getProfilesCount();
    /**
     * <code>repeated string profiles = 6;</code>
     */
    java.lang.String getProfiles(int index);
    /**
     * <code>repeated string profiles = 6;</code>
     */
    com.google.protobuf.ByteString
        getProfilesBytes(int index);
  }
  /**
   * Protobuf type {@code com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing}
   */
  public  static final class NodePing extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing)
      NodePingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodePing.newBuilder() to construct.
    private NodePing(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodePing() {
      birthday_ = "";
      id_ = "";
      endPoint_ = "";
      status_ = 0;
      profiles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodePing(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              birthday_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              id_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              endPoint_ = bs;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus value = com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                status_ = rawValue;
              }
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                profiles_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              profiles_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          profiles_ = profiles_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.internal_static_com_dunkware_trade_service_stream_protocol_cluster_protocol_NodePing_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.internal_static_com_dunkware_trade_service_stream_protocol_cluster_protocol_NodePing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.class, com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.Builder.class);
    }

    /**
     * Protobuf enum {@code com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing.NodePingStatus}
     */
    public enum NodePingStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Healthy = 0;</code>
       */
      Healthy(0),
      /**
       * <code>Overloaded = 1;</code>
       */
      Overloaded(1),
      /**
       * <code>Unresponsive = 2;</code>
       */
      Unresponsive(2),
      ;

      /**
       * <code>Healthy = 0;</code>
       */
      public static final int Healthy_VALUE = 0;
      /**
       * <code>Overloaded = 1;</code>
       */
      public static final int Overloaded_VALUE = 1;
      /**
       * <code>Unresponsive = 2;</code>
       */
      public static final int Unresponsive_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NodePingStatus valueOf(int value) {
        return forNumber(value);
      }

      public static NodePingStatus forNumber(int value) {
        switch (value) {
          case 0: return Healthy;
          case 1: return Overloaded;
          case 2: return Unresponsive;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NodePingStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NodePingStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NodePingStatus>() {
              public NodePingStatus findValueByNumber(int number) {
                return NodePingStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.getDescriptor().getEnumTypes().get(0);
      }

      private static final NodePingStatus[] VALUES = values();

      public static NodePingStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NodePingStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing.NodePingStatus)
    }

    private int bitField0_;
    public static final int BIRTHDAY_FIELD_NUMBER = 1;
    private volatile java.lang.Object birthday_;
    /**
     * <code>required string birthday = 1;</code>
     */
    public boolean hasBirthday() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string birthday = 1;</code>
     */
    public java.lang.String getBirthday() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          birthday_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string birthday = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBirthdayBytes() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthday_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string id = 3;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDPOINT_FIELD_NUMBER = 4;
    private volatile java.lang.Object endPoint_;
    /**
     * <code>required string endPoint = 4;</code>
     */
    public boolean hasEndPoint() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string endPoint = 4;</code>
     */
    public java.lang.String getEndPoint() {
      java.lang.Object ref = endPoint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endPoint_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string endPoint = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEndPointBytes() {
      java.lang.Object ref = endPoint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endPoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 5;
    private int status_;
    /**
     * <code>required .com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing.NodePingStatus status = 5;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing.NodePingStatus status = 5;</code>
     */
    public com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus getStatus() {
      com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus result = com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus.valueOf(status_);
      return result == null ? com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus.Healthy : result;
    }

    public static final int PROFILES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList profiles_;
    /**
     * <code>repeated string profiles = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getProfilesList() {
      return profiles_;
    }
    /**
     * <code>repeated string profiles = 6;</code>
     */
    public int getProfilesCount() {
      return profiles_.size();
    }
    /**
     * <code>repeated string profiles = 6;</code>
     */
    public java.lang.String getProfiles(int index) {
      return profiles_.get(index);
    }
    /**
     * <code>repeated string profiles = 6;</code>
     */
    public com.google.protobuf.ByteString
        getProfilesBytes(int index) {
      return profiles_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBirthday()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndPoint()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, birthday_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, endPoint_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(5, status_);
      }
      for (int i = 0; i < profiles_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, profiles_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, birthday_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, endPoint_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, status_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < profiles_.size(); i++) {
          dataSize += computeStringSizeNoTag(profiles_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getProfilesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing)) {
        return super.equals(obj);
      }
      com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing other = (com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing) obj;

      boolean result = true;
      result = result && (hasBirthday() == other.hasBirthday());
      if (hasBirthday()) {
        result = result && getBirthday()
            .equals(other.getBirthday());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasEndPoint() == other.hasEndPoint());
      if (hasEndPoint()) {
        result = result && getEndPoint()
            .equals(other.getEndPoint());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && status_ == other.status_;
      }
      result = result && getProfilesList()
          .equals(other.getProfilesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBirthday()) {
        hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
        hash = (53 * hash) + getBirthday().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasEndPoint()) {
        hash = (37 * hash) + ENDPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getEndPoint().hashCode();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      if (getProfilesCount() > 0) {
        hash = (37 * hash) + PROFILES_FIELD_NUMBER;
        hash = (53 * hash) + getProfilesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing)
        com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.internal_static_com_dunkware_trade_service_stream_protocol_cluster_protocol_NodePing_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.internal_static_com_dunkware_trade_service_stream_protocol_cluster_protocol_NodePing_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.class, com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.Builder.class);
      }

      // Construct using com.dunkware.trade.service.stream.protocol.cluster.protocol.ClusterProto.NodePing.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        birthday_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        endPoint_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        profiles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.internal_static_com_dunkware_trade_service_stream_protocol_cluster_protocol_NodePing_descriptor;
      }

      public com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing getDefaultInstanceForType() {
        return com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.getDefaultInstance();
      }

      public com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing build() {
        com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing buildPartial() {
        com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing result = new com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.birthday_ = birthday_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endPoint_ = endPoint_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          profiles_ = profiles_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.profiles_ = profiles_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing) {
          return mergeFrom((com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing other) {
        if (other == com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.getDefaultInstance()) return this;
        if (other.hasBirthday()) {
          bitField0_ |= 0x00000001;
          birthday_ = other.birthday_;
          onChanged();
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000002;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasEndPoint()) {
          bitField0_ |= 0x00000004;
          endPoint_ = other.endPoint_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (!other.profiles_.isEmpty()) {
          if (profiles_.isEmpty()) {
            profiles_ = other.profiles_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureProfilesIsMutable();
            profiles_.addAll(other.profiles_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBirthday()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasEndPoint()) {
          return false;
        }
        if (!hasStatus()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object birthday_ = "";
      /**
       * <code>required string birthday = 1;</code>
       */
      public boolean hasBirthday() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string birthday = 1;</code>
       */
      public java.lang.String getBirthday() {
        java.lang.Object ref = birthday_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            birthday_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string birthday = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBirthdayBytes() {
        java.lang.Object ref = birthday_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthday_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string birthday = 1;</code>
       */
      public Builder setBirthday(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string birthday = 1;</code>
       */
      public Builder clearBirthday() {
        bitField0_ = (bitField0_ & ~0x00000001);
        birthday_ = getDefaultInstance().getBirthday();
        onChanged();
        return this;
      }
      /**
       * <code>required string birthday = 1;</code>
       */
      public Builder setBirthdayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        birthday_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string id = 3;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 3;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 3;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endPoint_ = "";
      /**
       * <code>required string endPoint = 4;</code>
       */
      public boolean hasEndPoint() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string endPoint = 4;</code>
       */
      public java.lang.String getEndPoint() {
        java.lang.Object ref = endPoint_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            endPoint_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string endPoint = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEndPointBytes() {
        java.lang.Object ref = endPoint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endPoint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string endPoint = 4;</code>
       */
      public Builder setEndPoint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        endPoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string endPoint = 4;</code>
       */
      public Builder clearEndPoint() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endPoint_ = getDefaultInstance().getEndPoint();
        onChanged();
        return this;
      }
      /**
       * <code>required string endPoint = 4;</code>
       */
      public Builder setEndPointBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        endPoint_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>required .com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing.NodePingStatus status = 5;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing.NodePingStatus status = 5;</code>
       */
      public com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus getStatus() {
        com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus result = com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus.valueOf(status_);
        return result == null ? com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus.Healthy : result;
      }
      /**
       * <code>required .com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing.NodePingStatus status = 5;</code>
       */
      public Builder setStatus(com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing.NodePingStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing.NodePingStatus status = 5;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList profiles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureProfilesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          profiles_ = new com.google.protobuf.LazyStringArrayList(profiles_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string profiles = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getProfilesList() {
        return profiles_.getUnmodifiableView();
      }
      /**
       * <code>repeated string profiles = 6;</code>
       */
      public int getProfilesCount() {
        return profiles_.size();
      }
      /**
       * <code>repeated string profiles = 6;</code>
       */
      public java.lang.String getProfiles(int index) {
        return profiles_.get(index);
      }
      /**
       * <code>repeated string profiles = 6;</code>
       */
      public com.google.protobuf.ByteString
          getProfilesBytes(int index) {
        return profiles_.getByteString(index);
      }
      /**
       * <code>repeated string profiles = 6;</code>
       */
      public Builder setProfiles(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProfilesIsMutable();
        profiles_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string profiles = 6;</code>
       */
      public Builder addProfiles(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProfilesIsMutable();
        profiles_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string profiles = 6;</code>
       */
      public Builder addAllProfiles(
          java.lang.Iterable<java.lang.String> values) {
        ensureProfilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, profiles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string profiles = 6;</code>
       */
      public Builder clearProfiles() {
        profiles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string profiles = 6;</code>
       */
      public Builder addProfilesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProfilesIsMutable();
        profiles_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing)
    }

    // @@protoc_insertion_point(class_scope:com.dunkware.trade.service.stream.protocol.cluster.protocol.NodePing)
    private static final com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing();
    }

    public static com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NodePing>
        PARSER = new com.google.protobuf.AbstractParser<NodePing>() {
      public NodePing parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NodePing(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodePing> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodePing> getParserForType() {
      return PARSER;
    }

    public com.dunkware.trade.service.stream.json.cluster.protocol.ClusterProto.NodePing getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dunkware_trade_service_stream_protocol_cluster_protocol_NodePing_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dunkware_trade_service_stream_protocol_cluster_protocol_NodePing_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcluster.proto\022;com.dunkware.trade.serv" +
      "ice.stream.protocol.cluster.protocol\"\363\001\n" +
      "\010NodePing\022\020\n\010birthday\030\001 \002(\t\022\n\n\002id\030\003 \002(\t\022" +
      "\020\n\010endPoint\030\004 \002(\t\022d\n\006status\030\005 \002(\0162T.com." +
      "dunkware.trade.service.stream.protocol.c" +
      "luster.protocol.NodePing.NodePingStatus\022" +
      "\020\n\010profiles\030\006 \003(\t\"?\n\016NodePingStatus\022\013\n\007H" +
      "ealthy\020\000\022\016\n\nOverloaded\020\001\022\020\n\014Unresponsive" +
      "\020\002BK\n;com.dunkware.trade.service.stream." +
      "protocol.cluster.protocolB\014ClusterProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_dunkware_trade_service_stream_protocol_cluster_protocol_NodePing_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dunkware_trade_service_stream_protocol_cluster_protocol_NodePing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dunkware_trade_service_stream_protocol_cluster_protocol_NodePing_descriptor,
        new java.lang.String[] { "Birthday", "Id", "EndPoint", "Status", "Profiles", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
