// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netdata.proto

package com.dunkware.net.proto.data;

/**
 * <pre>
 * Bean insert into the list
 * identifier is on the bean
 * </pre>
 *
 * Protobuf type {@code dunkware.data.GBeanInsert}
 */
public  final class GBeanInsert extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dunkware.data.GBeanInsert)
    GBeanInsertOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GBeanInsert.newBuilder() to construct.
  private GBeanInsert(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GBeanInsert() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GBeanInsert(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.dunkware.net.proto.data.GBean.Builder subBuilder = null;
            if (bean_ != null) {
              subBuilder = bean_.toBuilder();
            }
            bean_ = input.readMessage(com.dunkware.net.proto.data.GBean.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bean_);
              bean_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dunkware.net.proto.data.GDataProto.internal_static_dunkware_data_GBeanInsert_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dunkware.net.proto.data.GDataProto.internal_static_dunkware_data_GBeanInsert_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dunkware.net.proto.data.GBeanInsert.class, com.dunkware.net.proto.data.GBeanInsert.Builder.class);
  }

  public static final int BEAN_FIELD_NUMBER = 1;
  private com.dunkware.net.proto.data.GBean bean_;
  /**
   * <code>.dunkware.data.GBean bean = 1;</code>
   */
  public boolean hasBean() {
    return bean_ != null;
  }
  /**
   * <code>.dunkware.data.GBean bean = 1;</code>
   */
  public com.dunkware.net.proto.data.GBean getBean() {
    return bean_ == null ? com.dunkware.net.proto.data.GBean.getDefaultInstance() : bean_;
  }
  /**
   * <code>.dunkware.data.GBean bean = 1;</code>
   */
  public com.dunkware.net.proto.data.GBeanOrBuilder getBeanOrBuilder() {
    return getBean();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bean_ != null) {
      output.writeMessage(1, getBean());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bean_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBean());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dunkware.net.proto.data.GBeanInsert)) {
      return super.equals(obj);
    }
    com.dunkware.net.proto.data.GBeanInsert other = (com.dunkware.net.proto.data.GBeanInsert) obj;

    boolean result = true;
    result = result && (hasBean() == other.hasBean());
    if (hasBean()) {
      result = result && getBean()
          .equals(other.getBean());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBean()) {
      hash = (37 * hash) + BEAN_FIELD_NUMBER;
      hash = (53 * hash) + getBean().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dunkware.net.proto.data.GBeanInsert parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.data.GBeanInsert parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dunkware.net.proto.data.GBeanInsert prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Bean insert into the list
   * identifier is on the bean
   * </pre>
   *
   * Protobuf type {@code dunkware.data.GBeanInsert}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dunkware.data.GBeanInsert)
      com.dunkware.net.proto.data.GBeanInsertOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dunkware.net.proto.data.GDataProto.internal_static_dunkware_data_GBeanInsert_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dunkware.net.proto.data.GDataProto.internal_static_dunkware_data_GBeanInsert_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dunkware.net.proto.data.GBeanInsert.class, com.dunkware.net.proto.data.GBeanInsert.Builder.class);
    }

    // Construct using com.dunkware.net.proto.data.GBeanInsert.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (beanBuilder_ == null) {
        bean_ = null;
      } else {
        bean_ = null;
        beanBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dunkware.net.proto.data.GDataProto.internal_static_dunkware_data_GBeanInsert_descriptor;
    }

    @java.lang.Override
    public com.dunkware.net.proto.data.GBeanInsert getDefaultInstanceForType() {
      return com.dunkware.net.proto.data.GBeanInsert.getDefaultInstance();
    }

    @java.lang.Override
    public com.dunkware.net.proto.data.GBeanInsert build() {
      com.dunkware.net.proto.data.GBeanInsert result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dunkware.net.proto.data.GBeanInsert buildPartial() {
      com.dunkware.net.proto.data.GBeanInsert result = new com.dunkware.net.proto.data.GBeanInsert(this);
      if (beanBuilder_ == null) {
        result.bean_ = bean_;
      } else {
        result.bean_ = beanBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dunkware.net.proto.data.GBeanInsert) {
        return mergeFrom((com.dunkware.net.proto.data.GBeanInsert)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dunkware.net.proto.data.GBeanInsert other) {
      if (other == com.dunkware.net.proto.data.GBeanInsert.getDefaultInstance()) return this;
      if (other.hasBean()) {
        mergeBean(other.getBean());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dunkware.net.proto.data.GBeanInsert parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dunkware.net.proto.data.GBeanInsert) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.dunkware.net.proto.data.GBean bean_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dunkware.net.proto.data.GBean, com.dunkware.net.proto.data.GBean.Builder, com.dunkware.net.proto.data.GBeanOrBuilder> beanBuilder_;
    /**
     * <code>.dunkware.data.GBean bean = 1;</code>
     */
    public boolean hasBean() {
      return beanBuilder_ != null || bean_ != null;
    }
    /**
     * <code>.dunkware.data.GBean bean = 1;</code>
     */
    public com.dunkware.net.proto.data.GBean getBean() {
      if (beanBuilder_ == null) {
        return bean_ == null ? com.dunkware.net.proto.data.GBean.getDefaultInstance() : bean_;
      } else {
        return beanBuilder_.getMessage();
      }
    }
    /**
     * <code>.dunkware.data.GBean bean = 1;</code>
     */
    public Builder setBean(com.dunkware.net.proto.data.GBean value) {
      if (beanBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bean_ = value;
        onChanged();
      } else {
        beanBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dunkware.data.GBean bean = 1;</code>
     */
    public Builder setBean(
        com.dunkware.net.proto.data.GBean.Builder builderForValue) {
      if (beanBuilder_ == null) {
        bean_ = builderForValue.build();
        onChanged();
      } else {
        beanBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dunkware.data.GBean bean = 1;</code>
     */
    public Builder mergeBean(com.dunkware.net.proto.data.GBean value) {
      if (beanBuilder_ == null) {
        if (bean_ != null) {
          bean_ =
            com.dunkware.net.proto.data.GBean.newBuilder(bean_).mergeFrom(value).buildPartial();
        } else {
          bean_ = value;
        }
        onChanged();
      } else {
        beanBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dunkware.data.GBean bean = 1;</code>
     */
    public Builder clearBean() {
      if (beanBuilder_ == null) {
        bean_ = null;
        onChanged();
      } else {
        bean_ = null;
        beanBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dunkware.data.GBean bean = 1;</code>
     */
    public com.dunkware.net.proto.data.GBean.Builder getBeanBuilder() {
      
      onChanged();
      return getBeanFieldBuilder().getBuilder();
    }
    /**
     * <code>.dunkware.data.GBean bean = 1;</code>
     */
    public com.dunkware.net.proto.data.GBeanOrBuilder getBeanOrBuilder() {
      if (beanBuilder_ != null) {
        return beanBuilder_.getMessageOrBuilder();
      } else {
        return bean_ == null ?
            com.dunkware.net.proto.data.GBean.getDefaultInstance() : bean_;
      }
    }
    /**
     * <code>.dunkware.data.GBean bean = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dunkware.net.proto.data.GBean, com.dunkware.net.proto.data.GBean.Builder, com.dunkware.net.proto.data.GBeanOrBuilder> 
        getBeanFieldBuilder() {
      if (beanBuilder_ == null) {
        beanBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dunkware.net.proto.data.GBean, com.dunkware.net.proto.data.GBean.Builder, com.dunkware.net.proto.data.GBeanOrBuilder>(
                getBean(),
                getParentForChildren(),
                isClean());
        bean_ = null;
      }
      return beanBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dunkware.data.GBeanInsert)
  }

  // @@protoc_insertion_point(class_scope:dunkware.data.GBeanInsert)
  private static final com.dunkware.net.proto.data.GBeanInsert DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dunkware.net.proto.data.GBeanInsert();
  }

  public static com.dunkware.net.proto.data.GBeanInsert getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GBeanInsert>
      PARSER = new com.google.protobuf.AbstractParser<GBeanInsert>() {
    @java.lang.Override
    public GBeanInsert parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GBeanInsert(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GBeanInsert> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GBeanInsert> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dunkware.net.proto.data.GBeanInsert getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

