// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.dunkware.net.proto.data;

public interface GDateTimeValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.data.GDateTimeValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp value = 1;</code>
   */
  boolean hasValue();
  /**
   * <code>.google.protobuf.Timestamp value = 1;</code>
   */
  com.google.protobuf.Timestamp getValue();
  /**
   * <code>.google.protobuf.Timestamp value = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getValueOrBuilder();
}
