// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.dunkware.net.proto.stream;

public interface GEntityVarCriteriaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.data.GEntityVarCriteria)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string identifier = 1;</code>
   */
  java.lang.String getIdentifier();
  /**
   * <code>string identifier = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();

  /**
   * <code>.dunkware.core.GOperator operator = 2;</code>
   */
  int getOperatorValue();
  /**
   * <code>.dunkware.core.GOperator operator = 2;</code>
   */
  com.dunkware.net.proto.core.GOperator getOperator();

  /**
   * <code>double value = 3;</code>
   */
  double getValue();
}
