// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package com.dunkware.net.proto.stream;

/**
 * Protobuf type {@code dunkware.stream.GEntityCriteria}
 */
public  final class GEntityCriteria extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dunkware.stream.GEntityCriteria)
    GEntityCriteriaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GEntityCriteria.newBuilder() to construct.
  private GEntityCriteria(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GEntityCriteria() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GEntityCriteria(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.dunkware.net.proto.stream.GEntityVarCriteria.Builder subBuilder = null;
            if (criteriaCase_ == 1) {
              subBuilder = ((com.dunkware.net.proto.stream.GEntityVarCriteria) criteria_).toBuilder();
            }
            criteria_ =
                input.readMessage(com.dunkware.net.proto.stream.GEntityVarCriteria.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.dunkware.net.proto.stream.GEntityVarCriteria) criteria_);
              criteria_ = subBuilder.buildPartial();
            }
            criteriaCase_ = 1;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dunkware.net.proto.stream.GStreamProto.internal_static_dunkware_stream_GEntityCriteria_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dunkware.net.proto.stream.GStreamProto.internal_static_dunkware_stream_GEntityCriteria_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dunkware.net.proto.stream.GEntityCriteria.class, com.dunkware.net.proto.stream.GEntityCriteria.Builder.class);
  }

  private int criteriaCase_ = 0;
  private java.lang.Object criteria_;
  public enum CriteriaCase
      implements com.google.protobuf.Internal.EnumLite {
    VARCRITERIA(1),
    CRITERIA_NOT_SET(0);
    private final int value;
    private CriteriaCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CriteriaCase valueOf(int value) {
      return forNumber(value);
    }

    public static CriteriaCase forNumber(int value) {
      switch (value) {
        case 1: return VARCRITERIA;
        case 0: return CRITERIA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public CriteriaCase
  getCriteriaCase() {
    return CriteriaCase.forNumber(
        criteriaCase_);
  }

  public static final int VARCRITERIA_FIELD_NUMBER = 1;
  /**
   * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
   */
  public boolean hasVarCriteria() {
    return criteriaCase_ == 1;
  }
  /**
   * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
   */
  public com.dunkware.net.proto.stream.GEntityVarCriteria getVarCriteria() {
    if (criteriaCase_ == 1) {
       return (com.dunkware.net.proto.stream.GEntityVarCriteria) criteria_;
    }
    return com.dunkware.net.proto.stream.GEntityVarCriteria.getDefaultInstance();
  }
  /**
   * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
   */
  public com.dunkware.net.proto.stream.GEntityVarCriteriaOrBuilder getVarCriteriaOrBuilder() {
    if (criteriaCase_ == 1) {
       return (com.dunkware.net.proto.stream.GEntityVarCriteria) criteria_;
    }
    return com.dunkware.net.proto.stream.GEntityVarCriteria.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (criteriaCase_ == 1) {
      output.writeMessage(1, (com.dunkware.net.proto.stream.GEntityVarCriteria) criteria_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (criteriaCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.dunkware.net.proto.stream.GEntityVarCriteria) criteria_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dunkware.net.proto.stream.GEntityCriteria)) {
      return super.equals(obj);
    }
    com.dunkware.net.proto.stream.GEntityCriteria other = (com.dunkware.net.proto.stream.GEntityCriteria) obj;

    boolean result = true;
    result = result && getCriteriaCase().equals(
        other.getCriteriaCase());
    if (!result) return false;
    switch (criteriaCase_) {
      case 1:
        result = result && getVarCriteria()
            .equals(other.getVarCriteria());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (criteriaCase_) {
      case 1:
        hash = (37 * hash) + VARCRITERIA_FIELD_NUMBER;
        hash = (53 * hash) + getVarCriteria().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dunkware.net.proto.stream.GEntityCriteria parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.stream.GEntityCriteria parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dunkware.net.proto.stream.GEntityCriteria prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dunkware.stream.GEntityCriteria}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dunkware.stream.GEntityCriteria)
      com.dunkware.net.proto.stream.GEntityCriteriaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dunkware.net.proto.stream.GStreamProto.internal_static_dunkware_stream_GEntityCriteria_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dunkware.net.proto.stream.GStreamProto.internal_static_dunkware_stream_GEntityCriteria_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dunkware.net.proto.stream.GEntityCriteria.class, com.dunkware.net.proto.stream.GEntityCriteria.Builder.class);
    }

    // Construct using com.dunkware.net.proto.stream.GEntityCriteria.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      criteriaCase_ = 0;
      criteria_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dunkware.net.proto.stream.GStreamProto.internal_static_dunkware_stream_GEntityCriteria_descriptor;
    }

    @java.lang.Override
    public com.dunkware.net.proto.stream.GEntityCriteria getDefaultInstanceForType() {
      return com.dunkware.net.proto.stream.GEntityCriteria.getDefaultInstance();
    }

    @java.lang.Override
    public com.dunkware.net.proto.stream.GEntityCriteria build() {
      com.dunkware.net.proto.stream.GEntityCriteria result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dunkware.net.proto.stream.GEntityCriteria buildPartial() {
      com.dunkware.net.proto.stream.GEntityCriteria result = new com.dunkware.net.proto.stream.GEntityCriteria(this);
      if (criteriaCase_ == 1) {
        if (varCriteriaBuilder_ == null) {
          result.criteria_ = criteria_;
        } else {
          result.criteria_ = varCriteriaBuilder_.build();
        }
      }
      result.criteriaCase_ = criteriaCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dunkware.net.proto.stream.GEntityCriteria) {
        return mergeFrom((com.dunkware.net.proto.stream.GEntityCriteria)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dunkware.net.proto.stream.GEntityCriteria other) {
      if (other == com.dunkware.net.proto.stream.GEntityCriteria.getDefaultInstance()) return this;
      switch (other.getCriteriaCase()) {
        case VARCRITERIA: {
          mergeVarCriteria(other.getVarCriteria());
          break;
        }
        case CRITERIA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dunkware.net.proto.stream.GEntityCriteria parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dunkware.net.proto.stream.GEntityCriteria) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int criteriaCase_ = 0;
    private java.lang.Object criteria_;
    public CriteriaCase
        getCriteriaCase() {
      return CriteriaCase.forNumber(
          criteriaCase_);
    }

    public Builder clearCriteria() {
      criteriaCase_ = 0;
      criteria_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.dunkware.net.proto.stream.GEntityVarCriteria, com.dunkware.net.proto.stream.GEntityVarCriteria.Builder, com.dunkware.net.proto.stream.GEntityVarCriteriaOrBuilder> varCriteriaBuilder_;
    /**
     * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
     */
    public boolean hasVarCriteria() {
      return criteriaCase_ == 1;
    }
    /**
     * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
     */
    public com.dunkware.net.proto.stream.GEntityVarCriteria getVarCriteria() {
      if (varCriteriaBuilder_ == null) {
        if (criteriaCase_ == 1) {
          return (com.dunkware.net.proto.stream.GEntityVarCriteria) criteria_;
        }
        return com.dunkware.net.proto.stream.GEntityVarCriteria.getDefaultInstance();
      } else {
        if (criteriaCase_ == 1) {
          return varCriteriaBuilder_.getMessage();
        }
        return com.dunkware.net.proto.stream.GEntityVarCriteria.getDefaultInstance();
      }
    }
    /**
     * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
     */
    public Builder setVarCriteria(com.dunkware.net.proto.stream.GEntityVarCriteria value) {
      if (varCriteriaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        criteria_ = value;
        onChanged();
      } else {
        varCriteriaBuilder_.setMessage(value);
      }
      criteriaCase_ = 1;
      return this;
    }
    /**
     * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
     */
    public Builder setVarCriteria(
        com.dunkware.net.proto.stream.GEntityVarCriteria.Builder builderForValue) {
      if (varCriteriaBuilder_ == null) {
        criteria_ = builderForValue.build();
        onChanged();
      } else {
        varCriteriaBuilder_.setMessage(builderForValue.build());
      }
      criteriaCase_ = 1;
      return this;
    }
    /**
     * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
     */
    public Builder mergeVarCriteria(com.dunkware.net.proto.stream.GEntityVarCriteria value) {
      if (varCriteriaBuilder_ == null) {
        if (criteriaCase_ == 1 &&
            criteria_ != com.dunkware.net.proto.stream.GEntityVarCriteria.getDefaultInstance()) {
          criteria_ = com.dunkware.net.proto.stream.GEntityVarCriteria.newBuilder((com.dunkware.net.proto.stream.GEntityVarCriteria) criteria_)
              .mergeFrom(value).buildPartial();
        } else {
          criteria_ = value;
        }
        onChanged();
      } else {
        if (criteriaCase_ == 1) {
          varCriteriaBuilder_.mergeFrom(value);
        }
        varCriteriaBuilder_.setMessage(value);
      }
      criteriaCase_ = 1;
      return this;
    }
    /**
     * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
     */
    public Builder clearVarCriteria() {
      if (varCriteriaBuilder_ == null) {
        if (criteriaCase_ == 1) {
          criteriaCase_ = 0;
          criteria_ = null;
          onChanged();
        }
      } else {
        if (criteriaCase_ == 1) {
          criteriaCase_ = 0;
          criteria_ = null;
        }
        varCriteriaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
     */
    public com.dunkware.net.proto.stream.GEntityVarCriteria.Builder getVarCriteriaBuilder() {
      return getVarCriteriaFieldBuilder().getBuilder();
    }
    /**
     * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
     */
    public com.dunkware.net.proto.stream.GEntityVarCriteriaOrBuilder getVarCriteriaOrBuilder() {
      if ((criteriaCase_ == 1) && (varCriteriaBuilder_ != null)) {
        return varCriteriaBuilder_.getMessageOrBuilder();
      } else {
        if (criteriaCase_ == 1) {
          return (com.dunkware.net.proto.stream.GEntityVarCriteria) criteria_;
        }
        return com.dunkware.net.proto.stream.GEntityVarCriteria.getDefaultInstance();
      }
    }
    /**
     * <code>.dunkware.stream.GEntityVarCriteria varCriteria = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dunkware.net.proto.stream.GEntityVarCriteria, com.dunkware.net.proto.stream.GEntityVarCriteria.Builder, com.dunkware.net.proto.stream.GEntityVarCriteriaOrBuilder> 
        getVarCriteriaFieldBuilder() {
      if (varCriteriaBuilder_ == null) {
        if (!(criteriaCase_ == 1)) {
          criteria_ = com.dunkware.net.proto.stream.GEntityVarCriteria.getDefaultInstance();
        }
        varCriteriaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dunkware.net.proto.stream.GEntityVarCriteria, com.dunkware.net.proto.stream.GEntityVarCriteria.Builder, com.dunkware.net.proto.stream.GEntityVarCriteriaOrBuilder>(
                (com.dunkware.net.proto.stream.GEntityVarCriteria) criteria_,
                getParentForChildren(),
                isClean());
        criteria_ = null;
      }
      criteriaCase_ = 1;
      onChanged();;
      return varCriteriaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dunkware.stream.GEntityCriteria)
  }

  // @@protoc_insertion_point(class_scope:dunkware.stream.GEntityCriteria)
  private static final com.dunkware.net.proto.stream.GEntityCriteria DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dunkware.net.proto.stream.GEntityCriteria();
  }

  public static com.dunkware.net.proto.stream.GEntityCriteria getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GEntityCriteria>
      PARSER = new com.google.protobuf.AbstractParser<GEntityCriteria>() {
    @java.lang.Override
    public GEntityCriteria parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GEntityCriteria(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GEntityCriteria> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GEntityCriteria> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dunkware.net.proto.stream.GEntityCriteria getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

