// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.dunkware.net.proto.stream;

/**
 * Protobuf type {@code dunkware.data.GEntitySignalCountCriteria}
 */
public  final class GEntitySignalCountCriteria extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dunkware.data.GEntitySignalCountCriteria)
    GEntitySignalCountCriteriaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GEntitySignalCountCriteria.newBuilder() to construct.
  private GEntitySignalCountCriteria(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GEntitySignalCountCriteria() {
    signalType_ = "";
    signalCount_ = 0;
    operator_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GEntitySignalCountCriteria(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            signalType_ = s;
            break;
          }
          case 16: {

            signalCount_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            operator_ = rawValue;
            break;
          }
          case 42: {
            com.dunkware.net.proto.core.GCalendarRange.Builder subBuilder = null;
            if (timeRange_ != null) {
              subBuilder = timeRange_.toBuilder();
            }
            timeRange_ = input.readMessage(com.dunkware.net.proto.core.GCalendarRange.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timeRange_);
              timeRange_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dunkware.net.proto.stream.GDataProto.internal_static_dunkware_data_GEntitySignalCountCriteria_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dunkware.net.proto.stream.GDataProto.internal_static_dunkware_data_GEntitySignalCountCriteria_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dunkware.net.proto.stream.GEntitySignalCountCriteria.class, com.dunkware.net.proto.stream.GEntitySignalCountCriteria.Builder.class);
  }

  public static final int SIGNALTYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object signalType_;
  /**
   * <code>string signalType = 1;</code>
   */
  public java.lang.String getSignalType() {
    java.lang.Object ref = signalType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      signalType_ = s;
      return s;
    }
  }
  /**
   * <code>string signalType = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSignalTypeBytes() {
    java.lang.Object ref = signalType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signalType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNALCOUNT_FIELD_NUMBER = 2;
  private int signalCount_;
  /**
   * <code>int32 signalCount = 2;</code>
   */
  public int getSignalCount() {
    return signalCount_;
  }

  public static final int OPERATOR_FIELD_NUMBER = 3;
  private int operator_;
  /**
   * <code>.dunkware.core.GOperator operator = 3;</code>
   */
  public int getOperatorValue() {
    return operator_;
  }
  /**
   * <code>.dunkware.core.GOperator operator = 3;</code>
   */
  public com.dunkware.net.proto.core.GOperator getOperator() {
    @SuppressWarnings("deprecation")
    com.dunkware.net.proto.core.GOperator result = com.dunkware.net.proto.core.GOperator.valueOf(operator_);
    return result == null ? com.dunkware.net.proto.core.GOperator.UNRECOGNIZED : result;
  }

  public static final int TIMERANGE_FIELD_NUMBER = 5;
  private com.dunkware.net.proto.core.GCalendarRange timeRange_;
  /**
   * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
   */
  public boolean hasTimeRange() {
    return timeRange_ != null;
  }
  /**
   * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
   */
  public com.dunkware.net.proto.core.GCalendarRange getTimeRange() {
    return timeRange_ == null ? com.dunkware.net.proto.core.GCalendarRange.getDefaultInstance() : timeRange_;
  }
  /**
   * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
   */
  public com.dunkware.net.proto.core.GCalendarRangeOrBuilder getTimeRangeOrBuilder() {
    return getTimeRange();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSignalTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, signalType_);
    }
    if (signalCount_ != 0) {
      output.writeInt32(2, signalCount_);
    }
    if (operator_ != com.dunkware.net.proto.core.GOperator.GT.getNumber()) {
      output.writeEnum(3, operator_);
    }
    if (timeRange_ != null) {
      output.writeMessage(5, getTimeRange());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSignalTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, signalType_);
    }
    if (signalCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, signalCount_);
    }
    if (operator_ != com.dunkware.net.proto.core.GOperator.GT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, operator_);
    }
    if (timeRange_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTimeRange());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dunkware.net.proto.stream.GEntitySignalCountCriteria)) {
      return super.equals(obj);
    }
    com.dunkware.net.proto.stream.GEntitySignalCountCriteria other = (com.dunkware.net.proto.stream.GEntitySignalCountCriteria) obj;

    boolean result = true;
    result = result && getSignalType()
        .equals(other.getSignalType());
    result = result && (getSignalCount()
        == other.getSignalCount());
    result = result && operator_ == other.operator_;
    result = result && (hasTimeRange() == other.hasTimeRange());
    if (hasTimeRange()) {
      result = result && getTimeRange()
          .equals(other.getTimeRange());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIGNALTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSignalType().hashCode();
    hash = (37 * hash) + SIGNALCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getSignalCount();
    hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
    hash = (53 * hash) + operator_;
    if (hasTimeRange()) {
      hash = (37 * hash) + TIMERANGE_FIELD_NUMBER;
      hash = (53 * hash) + getTimeRange().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dunkware.net.proto.stream.GEntitySignalCountCriteria prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dunkware.data.GEntitySignalCountCriteria}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dunkware.data.GEntitySignalCountCriteria)
      com.dunkware.net.proto.stream.GEntitySignalCountCriteriaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dunkware.net.proto.stream.GDataProto.internal_static_dunkware_data_GEntitySignalCountCriteria_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dunkware.net.proto.stream.GDataProto.internal_static_dunkware_data_GEntitySignalCountCriteria_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dunkware.net.proto.stream.GEntitySignalCountCriteria.class, com.dunkware.net.proto.stream.GEntitySignalCountCriteria.Builder.class);
    }

    // Construct using com.dunkware.net.proto.stream.GEntitySignalCountCriteria.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      signalType_ = "";

      signalCount_ = 0;

      operator_ = 0;

      if (timeRangeBuilder_ == null) {
        timeRange_ = null;
      } else {
        timeRange_ = null;
        timeRangeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dunkware.net.proto.stream.GDataProto.internal_static_dunkware_data_GEntitySignalCountCriteria_descriptor;
    }

    @java.lang.Override
    public com.dunkware.net.proto.stream.GEntitySignalCountCriteria getDefaultInstanceForType() {
      return com.dunkware.net.proto.stream.GEntitySignalCountCriteria.getDefaultInstance();
    }

    @java.lang.Override
    public com.dunkware.net.proto.stream.GEntitySignalCountCriteria build() {
      com.dunkware.net.proto.stream.GEntitySignalCountCriteria result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dunkware.net.proto.stream.GEntitySignalCountCriteria buildPartial() {
      com.dunkware.net.proto.stream.GEntitySignalCountCriteria result = new com.dunkware.net.proto.stream.GEntitySignalCountCriteria(this);
      result.signalType_ = signalType_;
      result.signalCount_ = signalCount_;
      result.operator_ = operator_;
      if (timeRangeBuilder_ == null) {
        result.timeRange_ = timeRange_;
      } else {
        result.timeRange_ = timeRangeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dunkware.net.proto.stream.GEntitySignalCountCriteria) {
        return mergeFrom((com.dunkware.net.proto.stream.GEntitySignalCountCriteria)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dunkware.net.proto.stream.GEntitySignalCountCriteria other) {
      if (other == com.dunkware.net.proto.stream.GEntitySignalCountCriteria.getDefaultInstance()) return this;
      if (!other.getSignalType().isEmpty()) {
        signalType_ = other.signalType_;
        onChanged();
      }
      if (other.getSignalCount() != 0) {
        setSignalCount(other.getSignalCount());
      }
      if (other.operator_ != 0) {
        setOperatorValue(other.getOperatorValue());
      }
      if (other.hasTimeRange()) {
        mergeTimeRange(other.getTimeRange());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dunkware.net.proto.stream.GEntitySignalCountCriteria parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dunkware.net.proto.stream.GEntitySignalCountCriteria) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object signalType_ = "";
    /**
     * <code>string signalType = 1;</code>
     */
    public java.lang.String getSignalType() {
      java.lang.Object ref = signalType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signalType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string signalType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSignalTypeBytes() {
      java.lang.Object ref = signalType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signalType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string signalType = 1;</code>
     */
    public Builder setSignalType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signalType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string signalType = 1;</code>
     */
    public Builder clearSignalType() {
      
      signalType_ = getDefaultInstance().getSignalType();
      onChanged();
      return this;
    }
    /**
     * <code>string signalType = 1;</code>
     */
    public Builder setSignalTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      signalType_ = value;
      onChanged();
      return this;
    }

    private int signalCount_ ;
    /**
     * <code>int32 signalCount = 2;</code>
     */
    public int getSignalCount() {
      return signalCount_;
    }
    /**
     * <code>int32 signalCount = 2;</code>
     */
    public Builder setSignalCount(int value) {
      
      signalCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 signalCount = 2;</code>
     */
    public Builder clearSignalCount() {
      
      signalCount_ = 0;
      onChanged();
      return this;
    }

    private int operator_ = 0;
    /**
     * <code>.dunkware.core.GOperator operator = 3;</code>
     */
    public int getOperatorValue() {
      return operator_;
    }
    /**
     * <code>.dunkware.core.GOperator operator = 3;</code>
     */
    public Builder setOperatorValue(int value) {
      operator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.dunkware.core.GOperator operator = 3;</code>
     */
    public com.dunkware.net.proto.core.GOperator getOperator() {
      @SuppressWarnings("deprecation")
      com.dunkware.net.proto.core.GOperator result = com.dunkware.net.proto.core.GOperator.valueOf(operator_);
      return result == null ? com.dunkware.net.proto.core.GOperator.UNRECOGNIZED : result;
    }
    /**
     * <code>.dunkware.core.GOperator operator = 3;</code>
     */
    public Builder setOperator(com.dunkware.net.proto.core.GOperator value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operator_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dunkware.core.GOperator operator = 3;</code>
     */
    public Builder clearOperator() {
      
      operator_ = 0;
      onChanged();
      return this;
    }

    private com.dunkware.net.proto.core.GCalendarRange timeRange_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dunkware.net.proto.core.GCalendarRange, com.dunkware.net.proto.core.GCalendarRange.Builder, com.dunkware.net.proto.core.GCalendarRangeOrBuilder> timeRangeBuilder_;
    /**
     * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
     */
    public boolean hasTimeRange() {
      return timeRangeBuilder_ != null || timeRange_ != null;
    }
    /**
     * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
     */
    public com.dunkware.net.proto.core.GCalendarRange getTimeRange() {
      if (timeRangeBuilder_ == null) {
        return timeRange_ == null ? com.dunkware.net.proto.core.GCalendarRange.getDefaultInstance() : timeRange_;
      } else {
        return timeRangeBuilder_.getMessage();
      }
    }
    /**
     * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
     */
    public Builder setTimeRange(com.dunkware.net.proto.core.GCalendarRange value) {
      if (timeRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeRange_ = value;
        onChanged();
      } else {
        timeRangeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
     */
    public Builder setTimeRange(
        com.dunkware.net.proto.core.GCalendarRange.Builder builderForValue) {
      if (timeRangeBuilder_ == null) {
        timeRange_ = builderForValue.build();
        onChanged();
      } else {
        timeRangeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
     */
    public Builder mergeTimeRange(com.dunkware.net.proto.core.GCalendarRange value) {
      if (timeRangeBuilder_ == null) {
        if (timeRange_ != null) {
          timeRange_ =
            com.dunkware.net.proto.core.GCalendarRange.newBuilder(timeRange_).mergeFrom(value).buildPartial();
        } else {
          timeRange_ = value;
        }
        onChanged();
      } else {
        timeRangeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
     */
    public Builder clearTimeRange() {
      if (timeRangeBuilder_ == null) {
        timeRange_ = null;
        onChanged();
      } else {
        timeRange_ = null;
        timeRangeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
     */
    public com.dunkware.net.proto.core.GCalendarRange.Builder getTimeRangeBuilder() {
      
      onChanged();
      return getTimeRangeFieldBuilder().getBuilder();
    }
    /**
     * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
     */
    public com.dunkware.net.proto.core.GCalendarRangeOrBuilder getTimeRangeOrBuilder() {
      if (timeRangeBuilder_ != null) {
        return timeRangeBuilder_.getMessageOrBuilder();
      } else {
        return timeRange_ == null ?
            com.dunkware.net.proto.core.GCalendarRange.getDefaultInstance() : timeRange_;
      }
    }
    /**
     * <code>.dunkware.core.GCalendarRange timeRange = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dunkware.net.proto.core.GCalendarRange, com.dunkware.net.proto.core.GCalendarRange.Builder, com.dunkware.net.proto.core.GCalendarRangeOrBuilder> 
        getTimeRangeFieldBuilder() {
      if (timeRangeBuilder_ == null) {
        timeRangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dunkware.net.proto.core.GCalendarRange, com.dunkware.net.proto.core.GCalendarRange.Builder, com.dunkware.net.proto.core.GCalendarRangeOrBuilder>(
                getTimeRange(),
                getParentForChildren(),
                isClean());
        timeRange_ = null;
      }
      return timeRangeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dunkware.data.GEntitySignalCountCriteria)
  }

  // @@protoc_insertion_point(class_scope:dunkware.data.GEntitySignalCountCriteria)
  private static final com.dunkware.net.proto.stream.GEntitySignalCountCriteria DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dunkware.net.proto.stream.GEntitySignalCountCriteria();
  }

  public static com.dunkware.net.proto.stream.GEntitySignalCountCriteria getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GEntitySignalCountCriteria>
      PARSER = new com.google.protobuf.AbstractParser<GEntitySignalCountCriteria>() {
    @java.lang.Override
    public GEntitySignalCountCriteria parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GEntitySignalCountCriteria(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GEntitySignalCountCriteria> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GEntitySignalCountCriteria> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dunkware.net.proto.stream.GEntitySignalCountCriteria getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

