// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package com.dunkware.net.proto.stream;

public interface GInstrumentVarsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.stream.GInstrumentVarsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string identifier = 1;</code>
   */
  java.lang.String getIdentifier();
  /**
   * <code>string identifier = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();
}
