// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package com.dunkware.net.proto.stream;

public interface GStreamSessionStartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dunkware.stream.GStreamSessionStart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp time = 1;</code>
   */
  boolean hasTime();
  /**
   * <code>.google.protobuf.Timestamp time = 1;</code>
   */
  com.google.protobuf.Timestamp getTime();
  /**
   * <code>.google.protobuf.Timestamp time = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

  /**
   * <code>.dunkware.stream.GStreamSessionSpec session = 2;</code>
   */
  boolean hasSession();
  /**
   * <code>.dunkware.stream.GStreamSessionSpec session = 2;</code>
   */
  com.dunkware.net.proto.stream.GStreamSessionSpec getSession();
  /**
   * <code>.dunkware.stream.GStreamSessionSpec session = 2;</code>
   */
  com.dunkware.net.proto.stream.GStreamSessionSpecOrBuilder getSessionOrBuilder();
}
